/**
 * The studio's emails in the seven languages beside English (see `emails.ts`).
 * `{{…}}` variables are kept exactly as they are in English.
 */
import type { EmailWords } from "./emails.ts";
import type { Tag } from "./labels.ts";

const FOOT_TAIL = "{{practice.name}} · {{practice.reply_to}} · {{practice.phone}}.";

export const EMAIL_TRANSLATIONS: Record<Exclude<Tag, "en-US">, EmailWords> = {
  "de-DE": {
    greeting: "Hallo {{recipient.first_name}},",
    clientFoot: `${FOOT_TAIL} Antworten Sie einfach auf diese E-Mail – einer von uns liest sie.`,
    studioFoot: "Gesendet von {{practice.name}} an {{practice.reply_to}}. Was wir Ihnen melden, ändern Sie in den Einstellungen.",
    "proposal-sent": {
      name: "Angebot gesendet",
      subject: "Angebot für {{client.company}} — {{proposal.number}}",
      preheader: "{{proposal.title}} · {{proposal.total}}",
      paras: [
        "Hier ist unser Angebot für {{proposal.title}}: was es umfasst, was es kostet und wie es bezahlt wird.",
        "Wenn es für Sie passt, nehmen Sie es im Portal an und unterschreiben mit Ihrem Namen. Ablehnen ist eine ganz normale Antwort, und Sie können uns an derselben Stelle sagen, warum.",
      ],
      button: "{{proposal.number}} lesen",
    },
    "proposal-reminder": {
      name: "Erinnerung an ein Angebot",
      subject: "{{proposal.number}} gilt bis {{proposal.valid_until.date}}",
      paras: [
        "Eine kurze Nachricht, falls unser Angebot für {{proposal.title}} untergegangen ist. Es gilt bis {{proposal.valid_until.date}}.",
        "Nehmen Sie es im Portal an und unterschreiben Sie, oder sagen Sie uns, was es für Sie passend machen würde.",
      ],
      button: "{{proposal.number}} lesen",
    },
    "new-work": {
      name: "Neue Arbeit zur Durchsicht",
      subject: "Neue Arbeit zum Ansehen — {{project.name}}",
      paras: ["In {{project.name}} ist neue Arbeit bereit, die Sie sich ansehen können.", "Geben Sie sie frei oder sagen Sie uns, was sich ändern soll — beides hilft uns."],
      button: "Jetzt ansehen",
    },
    handover: {
      name: "Übergabe",
      subject: "Alles aus {{project.name}}",
      paras: [
        "{{project.number}} ist abgeschlossen. Alles liegt auf einer Seite — die Entwürfe, die Quelldateien, die Schriften und eine Notiz dazu, was beim nächsten Druck zu beachten ist.",
        "Sie können den Link an Ihre Druckerei weiterleiten. Er öffnet sich ohne Anmeldung.",
      ],
      button: "Übergabe öffnen",
    },
    "enquiry-reply": {
      name: "Antwort auf eine Anfrage",
      subject: "Re: Ihre Nachricht an {{practice.name}}",
      paras: [
        "Vielen Dank für Ihre Nachricht.",
        "Könnten wir nächste Woche eine halbe Stunde sprechen? Danach schicken wir Ihnen ein kurzes Angebot, meist innerhalb weniger Tage.",
      ],
    },
    "ask-to-sign": {
      name: "Bitte um Unterschrift",
      subject: "Eine Sache zum Unterschreiben für {{proposal.number}}",
      paras: [
        "Sie haben {{proposal.title}} angenommen, bevor wir das Portal genutzt haben. Könnten Sie es dort unterschreiben? Es dauert eine Minute — Sie lesen die Bedingungen und tippen Ihren Namen.",
      ],
      button: "Lesen und unterschreiben",
    },
    "invoice-sent": {
      name: "Rechnung gesendet",
      subject: "{{invoice.number}} von {{practice.name}} — {{invoice.total}}",
      preheader: "Fällig am {{invoice.due_on.date}} · {{invoice.total}}",
      paras: ["Hier ist {{invoice.number}} — {{invoice.title}}."],
      list: ["{{invoice.number}} · fällig am {{invoice.due_on.date}} · {{invoice.total}}"],
      box: { label: "So bezahlen Sie", value: "{{addOn.invoices.payment_instructions}}" },
      reference: "Verwendungszweck: {{invoice.number}}",
      button: "{{invoice.number}} ansehen",
    },
    "invoice-rung-1": {
      name: "Erste Erinnerung",
      subject: "{{invoice.number}} — falls es untergegangen ist",
      paras: [
        "Kein Grund zur Sorge — {{invoice.number}} war am {{invoice.due_on.date}} fällig, und ich glaube, die Zahlung ist noch nicht eingegangen. Wenn sie schon in Ihrem Zahlungslauf ist, ignorieren Sie diese Nachricht einfach.",
        "{{invoice.balance}} für {{invoice.title}}.",
      ],
      button: "{{invoice.number}} ansehen",
    },
    "invoice-rung-2": {
      name: "Zweite Erinnerung",
      subject: "{{invoice.number}} ist jetzt {{invoice.due_on.days_since}} Tage überfällig",
      paras: [
        "{{invoice.number}} ist {{invoice.due_on.days_since}} Tage überfällig — {{invoice.balance}} sind offen. Können Sie mir sagen, wann bezahlt wird oder ob wir den Betrag aufteilen sollen?",
        "Teilzahlungen sind kein Problem und schnell eingerichtet. Nur Schweigen macht die Sache unangenehm.",
      ],
      button: "{{invoice.number}} ansehen",
    },
    "invoice-rung-3": {
      name: "Dritte Erinnerung",
      subject: "{{invoice.number}} ist {{invoice.due_on.days_since}} Tage überfällig — unsere Arbeit pausiert bis zur Zahlung",
      paras: [
        "{{invoice.number}} ist {{invoice.due_on.days_since}} Tage überfällig — {{invoice.balance}} sind offen. Nach Klausel 6 der vereinbarten Bedingungen pausiert ab heute jede Arbeit, die wir für Sie laufen haben, statt weiter gegen eine unbezahlte Rechnung aufzulaufen. Das ist nichts Persönliches.",
        "Es geht nichts verloren. Sobald sie beglichen ist, machen wir dort weiter, wo wir aufgehört haben.",
      ],
      button: "{{invoice.number}} ansehen",
    },
    "payment-receipt": {
      name: "Quittung",
      subject: "Vielen Dank — wir haben {{payment.amount}} erhalten",
      paras: ["Vielen Dank — wir haben am {{payment.paid_on.date}} {{payment.amount}} für {{invoice.number}} erhalten."],
      list: ["{{payment.number}} · für {{invoice.number}} · {{payment.amount}}", "Restbetrag · fällig am {{invoice.due_on.date}} · {{invoice.balance}}"],
      button: "Quittung ansehen",
    },
    "accepted-and-signed": {
      name: "Angenommen und unterschrieben",
      subject: "{{client.contact_name}} hat {{proposal.number}} angenommen und unterschrieben",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.contact_name}} von {{client.company}} hat den eigenen Namen eingetippt und das Angebot im Portal angenommen. Die vereinbarten Bedingungen sind am Datensatz festgehalten."],
      button: "Projekt beginnen",
    },
    declined: {
      name: "Abgelehnt",
      subject: "{{client.contact_name}} hat {{proposal.number}} abgelehnt",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.contact_name}} von {{client.company}} hat es abgelehnt. Die Notiz dazu:", "{{proposal.decline_note}}"],
      button: "{{proposal.number}} öffnen",
    },
    "asked-for-a-new-price": {
      name: "Neuer Preis angefragt",
      subject: "{{client.contact_name}} fragt einen neuen Preis für {{proposal.number}} an",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["Es galt bis {{proposal.valid_until.date}}. {{client.contact_name}} von {{client.company}} hätte gern einen neuen Preis dafür."],
      button: "{{proposal.number}} öffnen",
    },
    "changes-requested": {
      name: "Änderungen erbeten",
      subject: "{{client.contact_name}} bittet um Änderungen an {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} hat {{deliverable.title}} zurückgeschickt. Die Notiz dazu:", "{{deliverable.review_note}}"],
      button: "Durchsicht öffnen",
    },
    approved: {
      name: "Freigegeben",
      subject: "{{client.contact_name}} hat {{deliverable.title}} freigegeben",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} hat {{deliverable.title}} am {{deliverable.approved_on.date}} im Portal freigegeben."],
      button: "Projekt öffnen",
    },
    "new-note": {
      name: "Neue Notiz eines Kunden",
      subject: "Eine Notiz von {{client.contact_name}} zu {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} hat eine Notiz zu {{deliverable.title}} geschrieben. Sie steht in der Durchsicht, neben der angesehenen Version."],
      button: "Durchsicht öffnen",
    },
    "client-says-paid": {
      name: "Kunde meldet Zahlung",
      subject: "{{client.contact_name}} meldet eine Zahlung für {{invoice.number}}",
      lead: "{{invoice.number}} — {{invoice.title}}",
      paras: [
        "{{client.contact_name}} hat nach eigener Angabe am {{invoice.client_paid_on.date}} {{invoice.client_paid_amount}} überwiesen. Erfasst wird nichts, bis einer von uns das Konto prüft und die Zahlung einträgt.",
        "{{invoice.client_paid_note}}",
      ],
      button: "Zahlung erfassen",
    },
    "brief-sent": {
      name: "Briefing gesendet",
      subject: "{{client.company}} hat das Briefing gesendet",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} hat die Fragen zum Projektstart beantwortet. Die Antworten stehen auf der Projektseite unter Ihr Briefing."],
      button: "Projekt öffnen",
    },
    "new-enquiry": {
      name: "Neue Anfrage",
      subject: "Eine neue Anfrage von {{enquiry.name}}",
      lead: "{{enquiry.number}} — {{enquiry.business}}",
      paras: ["{{enquiry.name}} hat über das Formular auf Ihrer Website geschrieben. Die Nachricht:", "{{enquiry.body}}"],
      button: "Anfragen öffnen",
    },
  },
  "fr-FR": {
    greeting: "Bonjour {{recipient.first_name}},",
    clientFoot: `${FOOT_TAIL} Répondez à cet e-mail : l’un de nous le lira.`,
    studioFoot: "Envoyé par {{practice.name}} à {{practice.reply_to}}. Choisissez ce que nous vous signalons dans les réglages.",
    "proposal-sent": {
      name: "Proposition envoyée",
      subject: "Proposition pour {{client.company}} — {{proposal.number}}",
      preheader: "{{proposal.title}} · {{proposal.total}}",
      paras: [
        "Voici notre proposition pour {{proposal.title}} : ce qu’elle comprend, ce qu’elle coûte et comment elle se paie.",
        "Si elle vous convient, acceptez-la et signez-la dans le portail en tapant votre nom. Refuser est une réponse tout à fait normale, et vous pouvez nous dire pourquoi au même endroit.",
      ],
      button: "Lire {{proposal.number}}",
    },
    "proposal-reminder": {
      name: "Rappel de proposition",
      subject: "{{proposal.number}} est valable jusqu’au {{proposal.valid_until.date}}",
      paras: [
        "Un petit mot au cas où notre proposition pour {{proposal.title}} serait passée inaperçue. Elle est valable jusqu’au {{proposal.valid_until.date}}.",
        "Acceptez-la et signez-la dans le portail, ou dites-nous ce qui la rendrait possible.",
      ],
      button: "Lire {{proposal.number}}",
    },
    "new-work": {
      name: "Nouveau travail à relire",
      subject: "Du nouveau à regarder — {{project.name}}",
      paras: ["Un nouveau travail vous attend dans {{project.name}}.", "Validez-le, ou dites-nous ce qui doit changer — les deux nous aident."],
      button: "Relire maintenant",
    },
    handover: {
      name: "Remise des fichiers",
      subject: "Tout ce qui concerne {{project.name}}",
      paras: [
        "{{project.number}} est terminé. Tout est réuni sur une seule page : les visuels, les fichiers sources, les polices et une note sur ce qu’il faut faire pour la prochaine impression.",
        "Vous pouvez transférer le lien à votre imprimeur. Il s’ouvre sans connexion.",
      ],
      button: "Ouvrir la remise",
    },
    "enquiry-reply": {
      name: "Réponse à une demande",
      subject: "Re : votre message à {{practice.name}}",
      paras: [
        "Merci de nous avoir écrit.",
        "Pourrions-nous en parler une demi-heure la semaine prochaine ? Nous vous enverrons ensuite une courte proposition, généralement en quelques jours.",
      ],
    },
    "ask-to-sign": {
      name: "Demande de signature",
      subject: "Une chose à signer pour {{proposal.number}}",
      paras: [
        "Vous avez accepté {{proposal.title}} avant que nous utilisions le portail. Pourriez-vous la signer là-bas ? Cela prend une minute : vous lisez les conditions et tapez votre nom.",
      ],
      button: "Lire et signer",
    },
    "invoice-sent": {
      name: "Facture envoyée",
      subject: "{{invoice.number}} de {{practice.name}} — {{invoice.total}}",
      preheader: "Échéance le {{invoice.due_on.date}} · {{invoice.total}}",
      paras: ["Voici {{invoice.number}} — {{invoice.title}}."],
      list: ["{{invoice.number}} · échéance le {{invoice.due_on.date}} · {{invoice.total}}"],
      box: { label: "Comment payer", value: "{{addOn.invoices.payment_instructions}}" },
      reference: "Référence : {{invoice.number}}",
      button: "Voir {{invoice.number}}",
    },
    "invoice-rung-1": {
      name: "Premier rappel",
      subject: "{{invoice.number}} — au cas où elle vous aurait échappé",
      paras: [
        "Rien d’alarmant — {{invoice.number}} était due le {{invoice.due_on.date}} et je ne crois pas que le paiement soit arrivé. S’il est déjà dans votre prochain virement, ignorez simplement ce message.",
        "{{invoice.balance}} pour {{invoice.title}}.",
      ],
      button: "Voir {{invoice.number}}",
    },
    "invoice-rung-2": {
      name: "Deuxième rappel",
      subject: "{{invoice.number}} est en retard de {{invoice.due_on.days_since}} jours",
      paras: [
        "{{invoice.number}} est en retard de {{invoice.due_on.days_since}} jours — {{invoice.balance}} restent dus. Pouvez-vous me dire quand elle sera réglée, ou s’il faut l’étaler en deux ?",
        "Les paiements partiels sont possibles et simples à mettre en place. Seul le silence rend la chose gênante.",
      ],
      button: "Voir {{invoice.number}}",
    },
    "invoice-rung-3": {
      name: "Troisième rappel",
      subject: "{{invoice.number}} a {{invoice.due_on.days_since}} jours de retard — notre travail est en pause jusqu’au règlement",
      paras: [
        "{{invoice.number}} est en retard de {{invoice.due_on.days_since}} jours — {{invoice.balance}} restent dus. Selon la clause 6 des conditions que vous avez acceptées, tout travail en cours pour vous est mis en pause dès aujourd’hui plutôt que de s’accumuler face à une facture impayée. Ce n’est rien de personnel.",
        "Rien n’est perdu. Le jour où elle sera réglée, nous reprendrons là où nous nous sommes arrêtés.",
      ],
      button: "Voir {{invoice.number}}",
    },
    "payment-receipt": {
      name: "Reçu",
      subject: "Merci — nous avons reçu {{payment.amount}}",
      paras: ["Merci — nous avons reçu {{payment.amount}} pour {{invoice.number}} le {{payment.paid_on.date}}."],
      list: ["{{payment.number}} · pour {{invoice.number}} · {{payment.amount}}", "Reste dû · échéance le {{invoice.due_on.date}} · {{invoice.balance}}"],
      button: "Voir le reçu",
    },
    "accepted-and-signed": {
      name: "Acceptée et signée",
      subject: "{{client.contact_name}} a accepté et signé {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.contact_name}} chez {{client.company}} a tapé son nom et l’a acceptée dans le portail. Les conditions acceptées sont rattachées à la fiche."],
      button: "Démarrer le projet",
    },
    declined: {
      name: "Refusée",
      subject: "{{client.contact_name}} a refusé {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.contact_name}} chez {{client.company}} l’a refusée. Sa note :", "{{proposal.decline_note}}"],
      button: "Ouvrir {{proposal.number}}",
    },
    "asked-for-a-new-price": {
      name: "Nouveau prix demandé",
      subject: "{{client.contact_name}} demande un nouveau prix pour {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["Elle était valable jusqu’au {{proposal.valid_until.date}}. {{client.contact_name}} chez {{client.company}} aimerait un nouveau prix."],
      button: "Ouvrir {{proposal.number}}",
    },
    "changes-requested": {
      name: "Modifications demandées",
      subject: "{{client.contact_name}} demande des modifications sur {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} a renvoyé {{deliverable.title}}. Sa note :", "{{deliverable.review_note}}"],
      button: "Ouvrir la relecture",
    },
    approved: {
      name: "Validé",
      subject: "{{client.contact_name}} a validé {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} a validé {{deliverable.title}} dans le portail le {{deliverable.approved_on.date}}."],
      button: "Ouvrir le projet",
    },
    "new-note": {
      name: "Nouvelle note d’un client",
      subject: "Une note de {{client.contact_name}} sur {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} a écrit une note sur {{deliverable.title}}. Elle se trouve dans la relecture, à côté de la version consultée."],
      button: "Ouvrir la relecture",
    },
    "client-says-paid": {
      name: "Le client dit avoir payé",
      subject: "{{client.contact_name}} dit avoir payé {{invoice.number}}",
      lead: "{{invoice.number}} — {{invoice.title}}",
      paras: [
        "{{client.contact_name}} dit avoir envoyé {{invoice.client_paid_amount}} le {{invoice.client_paid_on.date}}. Rien n’est enregistré tant que l’un de nous n’a pas vérifié le compte et saisi le paiement.",
        "{{invoice.client_paid_note}}",
      ],
      button: "Enregistrer le paiement",
    },
    "brief-sent": {
      name: "Brief envoyé",
      subject: "{{client.company}} a envoyé son brief",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} a répondu aux questions de lancement. Les réponses sont sur la page du projet, sous Leur brief."],
      button: "Ouvrir le projet",
    },
    "new-enquiry": {
      name: "Nouvelle demande",
      subject: "Une nouvelle demande de {{enquiry.name}}",
      lead: "{{enquiry.number}} — {{enquiry.business}}",
      paras: ["{{enquiry.name}} a écrit via le formulaire de votre site. Son message :", "{{enquiry.body}}"],
      button: "Ouvrir les demandes",
    },
  },
  "da-DK": {
    greeting: "Hej {{recipient.first_name}},",
    clientFoot: `${FOOT_TAIL} Svar på denne e-mail, så læser en af os den.`,
    studioFoot: "Sendt af {{practice.name}} til {{practice.reply_to}}. Vælg, hvad vi fortæller dig, under Indstillinger.",
    "proposal-sent": {
      name: "Tilbud sendt",
      subject: "Tilbud til {{client.company}} — {{proposal.number}}",
      preheader: "{{proposal.title}} · {{proposal.total}}",
      paras: [
        "Her er vores tilbud på {{proposal.title}}: hvad det dækker, hvad det koster, og hvordan det betales.",
        "Hvis du er tilfreds med det, så accepter og underskriv det i portalen ved at skrive dit navn. Et nej er et helt normalt svar, og du kan fortælle os hvorfor samme sted.",
      ],
      button: "Læs {{proposal.number}}",
    },
    "proposal-reminder": {
      name: "Påmindelse om tilbud",
      subject: "{{proposal.number}} gælder til {{proposal.valid_until.date}}",
      paras: [
        "En kort besked, hvis vores tilbud på {{proposal.title}} er blevet væk i mængden. Det gælder til {{proposal.valid_until.date}}.",
        "Accepter og underskriv det i portalen, eller fortæl os, hvad der skal til for at det passer.",
      ],
      button: "Læs {{proposal.number}}",
    },
    "new-work": {
      name: "Nyt arbejde til gennemsyn",
      subject: "Nyt at kigge på — {{project.name}}",
      paras: ["Der er nyt arbejde klar til dig i {{project.name}}.", "Godkend det, eller fortæl os, hvad der skal ændres — begge dele hjælper."],
      button: "Se det nu",
    },
    handover: {
      name: "Aflevering",
      subject: "Alt fra {{project.name}}",
      paras: [
        "{{project.number}} er afsluttet. Det hele ligger på én side — grafikken, kildefilerne, skrifttyperne og en note om, hvad du skal gøre, når du trykker igen.",
        "Du kan sende linket videre til dit trykkeri. Det åbner uden login.",
      ],
      button: "Åbn afleveringen",
    },
    "enquiry-reply": {
      name: "Svar på en henvendelse",
      subject: "Sv: din besked til {{practice.name}}",
      paras: [
        "Tak fordi du skrev til os.",
        "Kunne vi tale sammen en halv time i næste uge? Bagefter sender vi dig et kort tilbud, som regel inden for et par dage.",
      ],
    },
    "ask-to-sign": {
      name: "Anmodning om underskrift",
      subject: "Én ting at underskrive for {{proposal.number}}",
      paras: [
        "Du accepterede {{proposal.title}}, før vi brugte portalen. Vil du underskrive det der? Det tager et minut — du læser vilkårene og skriver dit navn.",
      ],
      button: "Læs og underskriv",
    },
    "invoice-sent": {
      name: "Faktura sendt",
      subject: "{{invoice.number}} fra {{practice.name}} — {{invoice.total}}",
      preheader: "Forfalder {{invoice.due_on.date}} · {{invoice.total}}",
      paras: ["Her er {{invoice.number}} — {{invoice.title}}."],
      list: ["{{invoice.number}} · forfalder {{invoice.due_on.date}} · {{invoice.total}}"],
      box: { label: "Sådan betaler du", value: "{{addOn.invoices.payment_instructions}}" },
      reference: "Reference: {{invoice.number}}",
      button: "Se {{invoice.number}}",
    },
    "invoice-rung-1": {
      name: "Første påmindelse",
      subject: "{{invoice.number}} — hvis den er smuttet",
      paras: [
        "Ingen grund til bekymring — {{invoice.number}} forfaldt {{invoice.due_on.date}}, og jeg tror ikke, betalingen er kommet endnu. Hvis den allerede ligger i jeres betalingskørsel, så se bort fra denne besked.",
        "{{invoice.balance}} for {{invoice.title}}.",
      ],
      button: "Se {{invoice.number}}",
    },
    "invoice-rung-2": {
      name: "Anden påmindelse",
      subject: "{{invoice.number}} er nu {{invoice.due_on.days_since}} dage over forfald",
      paras: [
        "{{invoice.number}} er {{invoice.due_on.days_since}} dage over forfald — {{invoice.balance}} mangler. Kan du fortælle mig, hvornår den bliver betalt, eller om den skal deles i to?",
        "Delbetalinger er fint og nemme at sætte op. Det eneste, der gør det akavet, er stilhed.",
      ],
      button: "Se {{invoice.number}}",
    },
    "invoice-rung-3": {
      name: "Tredje påmindelse",
      subject: "{{invoice.number}} er {{invoice.due_on.days_since}} dage over forfald — vores arbejde holder pause, til den er betalt",
      paras: [
        "{{invoice.number}} er {{invoice.due_on.days_since}} dage over forfald — {{invoice.balance}} udestår. Efter punkt 6 i de vilkår, du accepterede, sættes alt arbejde, vi har i gang for dig, på pause fra i dag i stedet for at løbe op mod en ubetalt faktura. Det er ikke personligt.",
        "Intet går tabt. Den dag den er betalt, fortsætter vi, hvor vi slap.",
      ],
      button: "Se {{invoice.number}}",
    },
    "payment-receipt": {
      name: "Kvittering",
      subject: "Tak — vi har modtaget {{payment.amount}}",
      paras: ["Tak — vi modtog {{payment.amount}} for {{invoice.number}} den {{payment.paid_on.date}}."],
      list: ["{{payment.number}} · for {{invoice.number}} · {{payment.amount}}", "Restbeløb · forfalder {{invoice.due_on.date}} · {{invoice.balance}}"],
      button: "Se kvitteringen",
    },
    "accepted-and-signed": {
      name: "Accepteret og underskrevet",
      subject: "{{client.contact_name}} har accepteret og underskrevet {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.contact_name}} hos {{client.company}} skrev sit navn og accepterede tilbuddet i portalen. De accepterede vilkår er gemt på posten."],
      button: "Start projektet",
    },
    declined: {
      name: "Afvist",
      subject: "{{client.contact_name}} har afvist {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.contact_name}} hos {{client.company}} afviste det. Deres note:", "{{proposal.decline_note}}"],
      button: "Åbn {{proposal.number}}",
    },
    "asked-for-a-new-price": {
      name: "Bedt om en ny pris",
      subject: "{{client.contact_name}} beder om en ny pris på {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["Det gjaldt til {{proposal.valid_until.date}}. {{client.contact_name}} hos {{client.company}} vil gerne have en ny pris."],
      button: "Åbn {{proposal.number}}",
    },
    "changes-requested": {
      name: "Ændringer ønsket",
      subject: "{{client.contact_name}} ønsker ændringer i {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} sendte {{deliverable.title}} tilbage. Deres note:", "{{deliverable.review_note}}"],
      button: "Åbn gennemsynet",
    },
    approved: {
      name: "Godkendt",
      subject: "{{client.contact_name}} har godkendt {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} godkendte {{deliverable.title}} i portalen den {{deliverable.approved_on.date}}."],
      button: "Åbn projektet",
    },
    "new-note": {
      name: "Ny note fra en kunde",
      subject: "En note fra {{client.contact_name}} om {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} skrev en note om {{deliverable.title}}. Den står i gennemsynet ved den version, de så på."],
      button: "Åbn gennemsynet",
    },
    "client-says-paid": {
      name: "Kunden siger betalt",
      subject: "{{client.contact_name}} siger, at {{invoice.number}} er betalt",
      lead: "{{invoice.number}} — {{invoice.title}}",
      paras: [
        "{{client.contact_name}} siger, at de sendte {{invoice.client_paid_amount}} den {{invoice.client_paid_on.date}}. Intet registreres, før en af os har tjekket banken og registreret betalingen.",
        "{{invoice.client_paid_note}}",
      ],
      button: "Registrer betalingen",
    },
    "brief-sent": {
      name: "Brief sendt",
      subject: "{{client.company}} har sendt deres brief",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} har besvaret opstartsspørgsmålene. Svarene står på projektsiden under Deres brief."],
      button: "Åbn projektet",
    },
    "new-enquiry": {
      name: "Ny henvendelse",
      subject: "En ny henvendelse fra {{enquiry.name}}",
      lead: "{{enquiry.number}} — {{enquiry.business}}",
      paras: ["{{enquiry.name}} har skrevet via formularen på jeres website. Beskeden:", "{{enquiry.body}}"],
      button: "Åbn henvendelserne",
    },
  },
  "cs-CZ": {
    greeting: "Dobrý den, {{recipient.first_name}},",
    clientFoot: `${FOOT_TAIL} Odpovězte na tento e-mail a jeden z nás si ho přečte.`,
    studioFoot: "Odesláno ze studia {{practice.name}} na {{practice.reply_to}}. Co vám hlásíme, změníte v Nastavení.",
    "proposal-sent": {
      name: "Nabídka odeslána",
      subject: "{{client.company}}: nabídka {{proposal.number}}",
      preheader: "{{proposal.title}} · {{proposal.total}}",
      paras: [
        "Posíláme naši nabídku na {{proposal.title}}: co zahrnuje, kolik stojí a jak se platí.",
        "Pokud vám vyhovuje, přijměte ji a podepište v portálu napsáním svého jména. Odmítnutí je úplně běžná odpověď a na stejném místě nám můžete napsat proč.",
      ],
      button: "Přečíst {{proposal.number}}",
    },
    "proposal-reminder": {
      name: "Připomínka nabídky",
      subject: "{{proposal.number}} platí do {{proposal.valid_until.date}}",
      paras: [
        "Jen krátce připomínáme, kdyby vám naše nabídka na {{proposal.title}} zapadla. Platí do {{proposal.valid_until.date}}.",
        "Přijměte ji a podepište v portálu, nebo nám napište, co byste na ní potřebovali změnit.",
      ],
      button: "Přečíst {{proposal.number}}",
    },
    "new-work": {
      name: "Nová práce ke kontrole",
      subject: "Nová práce k prohlédnutí — {{project.name}}",
      paras: ["V projektu {{project.name}} na vás čeká nová práce k prohlédnutí.", "Schvalte ji, nebo nám napište, co změnit — pomůže nám obojí."],
      button: "Prohlédnout",
    },
    handover: {
      name: "Předání",
      subject: "Vše z projektu {{project.name}}",
      paras: [
        "{{project.number}} je uzavřen. Vše je na jedné stránce — grafika, zdrojové soubory, písma a poznámka, co dělat při dalším tisku.",
        "Odkaz můžete přeposlat své tiskárně. Otevře se bez přihlášení.",
      ],
      button: "Otevřít předání",
    },
    "enquiry-reply": {
      name: "Odpověď na poptávku",
      subject: "Re: vaše zpráva studiu {{practice.name}}",
      paras: [
        "Děkujeme, že jste se ozvali.",
        "Mohli bychom si příští týden na půl hodiny zavolat? Potom vám pošleme krátkou nabídku, obvykle během pár dní.",
      ],
    },
    "ask-to-sign": {
      name: "Žádost o podpis",
      subject: "K nabídce {{proposal.number}} chybí už jen váš podpis",
      paras: [
        "Nabídku {{proposal.title}} jste přijali dřív, než jsme začali používat portál. Mohli byste ji tam podepsat? Zabere to minutu — přečtete si podmínky a napíšete své jméno.",
      ],
      button: "Přečíst a podepsat",
    },
    "invoice-sent": {
      name: "Faktura odeslána",
      subject: "{{invoice.number}} od {{practice.name}} — {{invoice.total}}",
      preheader: "Splatnost {{invoice.due_on.date}} · {{invoice.total}}",
      paras: ["Posíláme {{invoice.number}} — {{invoice.title}}."],
      list: ["{{invoice.number}} · splatná {{invoice.due_on.date}} · {{invoice.total}}"],
      box: { label: "Jak zaplatit", value: "{{addOn.invoices.payment_instructions}}" },
      reference: "Variabilní symbol: {{invoice.number}}",
      button: "Zobrazit {{invoice.number}}",
    },
    "invoice-rung-1": {
      name: "První připomínka",
      subject: "{{invoice.number}} — kdyby vám unikla",
      paras: [
        "Nic vážného — {{invoice.number}} byla splatná {{invoice.due_on.date}} a myslím, že platba ještě nedorazila. Pokud už je v příštím platebním běhu, tuto zprávu klidně ignorujte.",
        "{{invoice.balance}} za {{invoice.title}}.",
      ],
      button: "Zobrazit {{invoice.number}}",
    },
    "invoice-rung-2": {
      name: "Druhá připomínka",
      subject: "{{invoice.number}} je {{invoice.due_on.days_since}} dní po splatnosti",
      paras: [
        "{{invoice.number}} je {{invoice.due_on.days_since}} dní po splatnosti — zbývá uhradit {{invoice.balance}}. Můžete mi napsat, kdy bude zaplacena, nebo jestli ji rozdělit na dvě části?",
        "Platba po částech není problém a snadno ji nastavíme. Nepříjemné je jen mlčení.",
      ],
      button: "Zobrazit {{invoice.number}}",
    },
    "invoice-rung-3": {
      name: "Třetí připomínka",
      subject: "{{invoice.number}} je {{invoice.due_on.days_since}} dní po splatnosti — naše práce stojí do úhrady",
      paras: [
        "{{invoice.number}} je {{invoice.due_on.days_since}} dní po splatnosti — zbývá uhradit {{invoice.balance}}. Podle bodu 6 podmínek, které jste přijali, od dnešního dne pozastavujeme veškerou práci, kterou máme rozběhnutou, místo abychom ji hromadili proti nezaplacené faktuře. Není to nic osobního.",
        "Nic se neztratí. Jakmile bude uhrazena, navážeme tam, kde jsme skončili.",
      ],
      button: "Zobrazit {{invoice.number}}",
    },
    "payment-receipt": {
      name: "Potvrzení o platbě",
      subject: "Děkujeme — obdrželi jsme {{payment.amount}}",
      paras: ["Děkujeme — dne {{payment.paid_on.date}} jsme obdrželi {{payment.amount}} na {{invoice.number}}."],
      list: ["{{payment.number}} · na {{invoice.number}} · {{payment.amount}}", "Zbývá · splatnost {{invoice.due_on.date}} · {{invoice.balance}}"],
      button: "Zobrazit potvrzení",
    },
    "accepted-and-signed": {
      name: "Přijato a podepsáno",
      subject: "{{client.contact_name}} přijal(a) a podepsal(a) {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.contact_name}} z {{client.company}} napsal(a) své jméno a přijal(a) nabídku v portálu. Přijaté podmínky jsou u záznamu uložené."],
      button: "Zahájit projekt",
    },
    declined: {
      name: "Odmítnuto",
      subject: "{{client.contact_name}} odmítl(a) {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.contact_name}} z {{client.company}} nabídku odmítl(a). Poznámka:", "{{proposal.decline_note}}"],
      button: "Otevřít {{proposal.number}}",
    },
    "asked-for-a-new-price": {
      name: "Žádost o novou cenu",
      subject: "{{client.contact_name}} žádá novou cenu za {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["Platila do {{proposal.valid_until.date}}. {{client.contact_name}} z {{client.company}} by rád(a) novou cenu."],
      button: "Otevřít {{proposal.number}}",
    },
    "changes-requested": {
      name: "Požadovány změny",
      subject: "{{client.contact_name}} žádá změny v {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} vrátil(a) {{deliverable.title}}. Poznámka:", "{{deliverable.review_note}}"],
      button: "Otevřít kontrolu",
    },
    approved: {
      name: "Schváleno",
      subject: "{{client.contact_name}} schválil(a) {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} schválil(a) {{deliverable.title}} v portálu dne {{deliverable.approved_on.date}}."],
      button: "Otevřít projekt",
    },
    "new-note": {
      name: "Nová poznámka od klienta",
      subject: "Poznámka od {{client.contact_name}} k {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} napsal(a) poznámku k {{deliverable.title}}. Najdete ji v kontrole u verze, kterou si prohlížel(a)."],
      button: "Otevřít kontrolu",
    },
    "client-says-paid": {
      name: "Klient uvádí platbu",
      subject: "{{client.contact_name}} uvádí, že zaplatil(a) {{invoice.number}}",
      lead: "{{invoice.number}} — {{invoice.title}}",
      paras: [
        "{{client.contact_name}} uvádí, že dne {{invoice.client_paid_on.date}} odeslal(a) {{invoice.client_paid_amount}}. Nic se nezaznamená, dokud jeden z nás nezkontroluje účet a platbu nezapíše.",
        "{{invoice.client_paid_note}}",
      ],
      button: "Zaznamenat platbu",
    },
    "brief-sent": {
      name: "Brief odeslán",
      subject: "{{client.company}} poslali svůj brief",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} odpověděl(a) na úvodní otázky. Odpovědi najdete na stránce projektu v části Jejich brief."],
      button: "Otevřít projekt",
    },
    "new-enquiry": {
      name: "Nová poptávka",
      subject: "Nová poptávka od {{enquiry.name}}",
      lead: "{{enquiry.number}} — {{enquiry.business}}",
      paras: ["Přes formulář na vašem webu přišla zpráva od {{enquiry.name}}. Zní takto:", "{{enquiry.body}}"],
      button: "Otevřít poptávky",
    },
  },
  "ar-EG": {
    greeting: "مرحبًا {{recipient.first_name}}،",
    clientFoot: `${FOOT_TAIL} رُدّ على هذه الرسالة وسيقرؤها أحدنا.`,
    studioFoot: "أرسلها {{practice.name}} إلى {{practice.reply_to}}. غيّر ما نُخبرك به من الإعدادات.",
    "proposal-sent": {
      name: "أُرسل العرض",
      subject: "عرض لـ {{client.company}} — {{proposal.number}}",
      preheader: "{{proposal.title}} · {{proposal.total}}",
      paras: [
        "إليك عرضنا لـ {{proposal.title}}: ما يشمله، وكم يكلّف، وكيف يُدفع.",
        "إن كان مناسبًا لك، فاقبله ووقّعه في البوابة بكتابة اسمك. الرفض جواب طبيعي تمامًا، ويمكنك أن تخبرنا بالسبب في المكان نفسه.",
      ],
      button: "اقرأ {{proposal.number}}",
    },
    "proposal-reminder": {
      name: "تذكير بالعرض",
      subject: "{{proposal.number}} صالح حتى {{proposal.valid_until.date}}",
      paras: [
        "رسالة قصيرة في حال ضاع عرضنا لـ {{proposal.title}} بين الرسائل. هو صالح حتى {{proposal.valid_until.date}}.",
        "اقبله ووقّعه في البوابة، أو أخبرنا بما يجعله مناسبًا لك.",
      ],
      button: "اقرأ {{proposal.number}}",
    },
    "new-work": {
      name: "عمل جديد للمراجعة",
      subject: "عمل جديد للاطلاع — {{project.name}}",
      paras: ["هناك عمل جديد جاهز لتطّلع عليه في {{project.name}}.", "اعتمده، أو أخبرنا بما يجب تغييره — كلاهما مفيد."],
      button: "راجِع الآن",
    },
    handover: {
      name: "التسليم",
      subject: "كل ما يخص {{project.name}}",
      paras: [
        "اكتمل {{project.number}}. كل شيء في صفحة واحدة: التصاميم والملفات المصدرية والخطوط وملاحظة بما يجب فعله عند الطباعة مرة أخرى.",
        "يمكنك إعادة توجيه الرابط إلى المطبعة. يُفتح دون تسجيل دخول.",
      ],
      button: "افتح التسليم",
    },
    "enquiry-reply": {
      name: "رد على استفسار",
      subject: "رد: رسالتك إلى {{practice.name}}",
      paras: ["شكرًا لتواصلك معنا.", "هل يمكننا التحدث نصف ساعة الأسبوع المقبل؟ سنعود إليك بعدها بعرض قصير، عادةً خلال أيام قليلة."],
    },
    "ask-to-sign": {
      name: "طلب التوقيع",
      subject: "أمر واحد للتوقيع على {{proposal.number}}",
      paras: ["لقد قبلتَ {{proposal.title}} قبل أن نستخدم البوابة. هل يمكنك توقيعه هناك؟ يستغرق الأمر دقيقة: تقرأ الشروط وتكتب اسمك."],
      button: "اقرأ ووقّع",
    },
    "invoice-sent": {
      name: "أُرسلت الفاتورة",
      subject: "{{invoice.number}} من {{practice.name}} — {{invoice.total}}",
      preheader: "تستحق في {{invoice.due_on.date}} · {{invoice.total}}",
      paras: ["إليك {{invoice.number}} — {{invoice.title}}."],
      list: ["{{invoice.number}} · تستحق في {{invoice.due_on.date}} · {{invoice.total}}"],
      box: { label: "طريقة الدفع", value: "{{addOn.invoices.payment_instructions}}" },
      reference: "المرجع: {{invoice.number}}",
      button: "اعرض {{invoice.number}}",
    },
    "invoice-rung-1": {
      name: "التذكير الأول",
      subject: "{{invoice.number}} — تحسّبًا لأنها فاتتك",
      paras: [
        "لا داعي للقلق — استحقّت {{invoice.number}} في {{invoice.due_on.date}} ولا أظن أن الدفعة وصلت بعد. إن كانت ضمن دفعاتك القادمة فتجاهل هذه الرسالة تمامًا.",
        "{{invoice.balance}} عن {{invoice.title}}.",
      ],
      button: "اعرض {{invoice.number}}",
    },
    "invoice-rung-2": {
      name: "التذكير الثاني",
      subject: "{{invoice.number}} متأخرة الآن {{invoice.due_on.days_since}} يومًا",
      paras: [
        "{{invoice.number}} متأخرة {{invoice.due_on.days_since}} يومًا — والمتبقي {{invoice.balance}}. هل يمكنك إخباري متى ستُدفع، أو إن كانت تحتاج إلى تقسيمها على دفعتين؟",
        "الدفع على أجزاء ممكن وسهل الترتيب. وحده الصمت يجعل الأمر محرجًا.",
      ],
      button: "اعرض {{invoice.number}}",
    },
    "invoice-rung-3": {
      name: "التذكير الثالث",
      subject: "{{invoice.number}} متأخرة {{invoice.due_on.days_since}} يومًا — يتوقف عملنا مؤقتًا حتى تُسدَّد",
      paras: [
        "{{invoice.number}} متأخرة {{invoice.due_on.days_since}} يومًا — والمستحق {{invoice.balance}}. وفق البند ٦ من الشروط التي وافقتَ عليها، يتوقف مؤقتًا من اليوم أي عمل جارٍ لك بدل أن يتراكم مقابل فاتورة غير مدفوعة. والأمر ليس شخصيًا.",
        "لن يضيع شيء. في اليوم الذي تُسدَّد فيه نكمل من حيث توقّفنا.",
      ],
      button: "اعرض {{invoice.number}}",
    },
    "payment-receipt": {
      name: "الإيصال",
      subject: "شكرًا — استلمنا {{payment.amount}}",
      paras: ["شكرًا — استلمنا {{payment.amount}} عن {{invoice.number}} في {{payment.paid_on.date}}."],
      list: ["{{payment.number}} · عن {{invoice.number}} · {{payment.amount}}", "المتبقي · يستحق في {{invoice.due_on.date}} · {{invoice.balance}}"],
      button: "اعرض الإيصال",
    },
    "accepted-and-signed": {
      name: "قُبل ووُقّع",
      subject: "{{client.contact_name}} قبل {{proposal.number}} ووقّعه",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["كتب {{client.contact_name}} من {{client.company}} اسمه وقبِل العرض في البوابة. الشروط التي وافق عليها مثبّتة في السجل."],
      button: "ابدأ المشروع",
    },
    declined: {
      name: "مرفوض",
      subject: "{{client.contact_name}} رفض {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["رفضه {{client.contact_name}} من {{client.company}}. ملاحظته:", "{{proposal.decline_note}}"],
      button: "افتح {{proposal.number}}",
    },
    "asked-for-a-new-price": {
      name: "طُلب سعر جديد",
      subject: "{{client.contact_name}} يطلب سعرًا جديدًا لـ {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["كان صالحًا حتى {{proposal.valid_until.date}}. يودّ {{client.contact_name}} من {{client.company}} سعرًا جديدًا له."],
      button: "افتح {{proposal.number}}",
    },
    "changes-requested": {
      name: "طُلبت تعديلات",
      subject: "{{client.contact_name}} يطلب تعديلات على {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["أعاد {{client.contact_name}} {{deliverable.title}}. ملاحظته:", "{{deliverable.review_note}}"],
      button: "افتح المراجعة",
    },
    approved: {
      name: "معتمد",
      subject: "{{client.contact_name}} اعتمد {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["اعتمد {{client.contact_name}} {{deliverable.title}} في البوابة في {{deliverable.approved_on.date}}."],
      button: "افتح المشروع",
    },
    "new-note": {
      name: "ملاحظة جديدة من عميل",
      subject: "ملاحظة من {{client.contact_name}} على {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["كتب {{client.contact_name}} ملاحظة على {{deliverable.title}}. تجدها في المراجعة بجانب الإصدار الذي اطّلع عليه."],
      button: "افتح المراجعة",
    },
    "client-says-paid": {
      name: "العميل يقول إنه دفع",
      subject: "{{client.contact_name}} يقول إنه دفع {{invoice.number}}",
      lead: "{{invoice.number}} — {{invoice.title}}",
      paras: [
        "يقول {{client.contact_name}} إنه أرسل {{invoice.client_paid_amount}} في {{invoice.client_paid_on.date}}. لا يُسجَّل شيء حتى يتحقق أحدنا من الحساب ويسجّل الدفعة.",
        "{{invoice.client_paid_note}}",
      ],
      button: "سجّل الدفعة",
    },
    "brief-sent": {
      name: "أُرسل الموجز",
      subject: "{{client.company}} أرسل الموجز",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["أجاب {{client.contact_name}} عن أسئلة الانطلاق. الإجابات في صفحة المشروع تحت «موجزهم»."],
      button: "افتح المشروع",
    },
    "new-enquiry": {
      name: "استفسار جديد",
      subject: "استفسار جديد من {{enquiry.name}}",
      lead: "{{enquiry.number}} — {{enquiry.business}}",
      paras: ["وصلت رسالة من {{enquiry.name}} عبر النموذج في موقعكم. نصّها:", "{{enquiry.body}}"],
      button: "افتح الاستفسارات",
    },
  },
  "zh-CN": {
    greeting: "{{recipient.first_name}}，您好：",
    clientFoot: `${FOOT_TAIL} 直接回复这封邮件，我们中会有人读到。`,
    studioFoot: "由 {{practice.name}} 发送至 {{practice.reply_to}}。在设置中更改我们通知您的内容。",
    "proposal-sent": {
      name: "提案已发送",
      subject: "给 {{client.company}} 的提案 — {{proposal.number}}",
      preheader: "{{proposal.title}} · {{proposal.total}}",
      paras: [
        "这是我们为 {{proposal.title}} 准备的提案：包含哪些内容、费用多少、如何付款。",
        "如果您满意，请在门户中输入您的姓名接受并签署。拒绝也完全正常，您可以在同一处告诉我们原因。",
      ],
      button: "阅读 {{proposal.number}}",
    },
    "proposal-reminder": {
      name: "提案提醒",
      subject: "{{proposal.number}} 有效期至 {{proposal.valid_until.date}}",
      paras: ["简单提醒一下，以防我们为 {{proposal.title}} 准备的提案被埋没了。它的有效期至 {{proposal.valid_until.date}}。", "请在门户中接受并签署，或告诉我们怎样才合适。"],
      button: "阅读 {{proposal.number}}",
    },
    "new-work": {
      name: "新作品待审阅",
      subject: "有新作品可以查看 — {{project.name}}",
      paras: ["{{project.name}} 中有新作品可供您查看。", "请批准，或告诉我们需要修改什么 — 两者都很有帮助。"],
      button: "立即审阅",
    },
    handover: {
      name: "交接",
      subject: "{{project.name}} 的全部内容",
      paras: ["{{project.number}} 已完成。所有内容都在一个页面上：设计稿、源文件、字体，以及下次印刷时的注意事项。", "您可以把链接转发给印刷厂。打开无需登录。"],
      button: "打开交接页",
    },
    "enquiry-reply": {
      name: "回复询价",
      subject: "回复：您发给 {{practice.name}} 的消息",
      paras: ["感谢您与我们联系。", "我们能否在下周通话半小时？之后我们会给您一份简短的提案，通常在几天之内。"],
    },
    "ask-to-sign": {
      name: "请求签署",
      subject: "{{proposal.number}} 有一项需要签署",
      paras: ["您在我们使用门户之前接受了 {{proposal.title}}。能否在门户中签署？只需一分钟：阅读条款并输入您的姓名。"],
      button: "阅读并签署",
    },
    "invoice-sent": {
      name: "发票已发送",
      subject: "来自 {{practice.name}} 的 {{invoice.number}} — {{invoice.total}}",
      preheader: "{{invoice.due_on.date}} 到期 · {{invoice.total}}",
      paras: ["这是 {{invoice.number}} — {{invoice.title}}。"],
      list: ["{{invoice.number}} · {{invoice.due_on.date}} 到期 · {{invoice.total}}"],
      box: { label: "付款方式", value: "{{addOn.invoices.payment_instructions}}" },
      reference: "付款备注：{{invoice.number}}",
      button: "查看 {{invoice.number}}",
    },
    "invoice-rung-1": {
      name: "第一次提醒",
      subject: "{{invoice.number}} — 以防您遗漏",
      paras: ["不必紧张 — {{invoice.number}} 已于 {{invoice.due_on.date}} 到期，我想款项还没有到账。如果已经在您的付款计划中，请忽略这封邮件。", "{{invoice.title}} 尚欠 {{invoice.balance}}。"],
      button: "查看 {{invoice.number}}",
    },
    "invoice-rung-2": {
      name: "第二次提醒",
      subject: "{{invoice.number}} 已逾期 {{invoice.due_on.days_since}} 天",
      paras: ["{{invoice.number}} 已逾期 {{invoice.due_on.days_since}} 天，尚欠 {{invoice.balance}}。能否告诉我何时付款，或者是否需要分两次付？", "分期付款没问题，也很容易安排。只有沉默才会让事情尴尬。"],
      button: "查看 {{invoice.number}}",
    },
    "invoice-rung-3": {
      name: "第三次提醒",
      subject: "{{invoice.number}} 已逾期 {{invoice.due_on.days_since}} 天——结清前我们的工作暂停",
      paras: [
        "{{invoice.number}} 已逾期 {{invoice.due_on.days_since}} 天，尚欠 {{invoice.balance}}。根据您同意的条款第 6 条，从今天起我们为您进行中的工作将暂停，而不是继续积压在一张未付的发票上。这并非针对个人。",
        "什么都不会丢失。款项结清的那天，我们就从停下的地方继续。",
      ],
      button: "查看 {{invoice.number}}",
    },
    "payment-receipt": {
      name: "收据",
      subject: "谢谢 — 我们已收到 {{payment.amount}}",
      paras: ["谢谢 — 我们已于 {{payment.paid_on.date}} 收到 {{invoice.number}} 的 {{payment.amount}}。"],
      list: ["{{payment.number}} · 用于 {{invoice.number}} · {{payment.amount}}", "剩余金额 · {{invoice.due_on.date}} 到期 · {{invoice.balance}}"],
      button: "查看收据",
    },
    "accepted-and-signed": {
      name: "已接受并签署",
      subject: "{{client.contact_name}} 已接受并签署 {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.company}} 的 {{client.contact_name}} 输入了姓名并在门户中接受了提案。所同意的条款已固定在记录中。"],
      button: "开始项目",
    },
    declined: {
      name: "已拒绝",
      subject: "{{client.contact_name}} 拒绝了 {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.company}} 的 {{client.contact_name}} 拒绝了提案。对方的说明：", "{{proposal.decline_note}}"],
      button: "打开 {{proposal.number}}",
    },
    "asked-for-a-new-price": {
      name: "已请求新报价",
      subject: "{{client.contact_name}} 请求为 {{proposal.number}} 重新报价",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["它的有效期至 {{proposal.valid_until.date}}。{{client.company}} 的 {{client.contact_name}} 希望得到新的报价。"],
      button: "打开 {{proposal.number}}",
    },
    "changes-requested": {
      name: "已要求修改",
      subject: "{{client.contact_name}} 要求修改 {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} 退回了 {{deliverable.title}}。对方的说明：", "{{deliverable.review_note}}"],
      button: "打开审阅",
    },
    approved: {
      name: "已批准",
      subject: "{{client.contact_name}} 批准了 {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} 于 {{deliverable.approved_on.date}} 在门户中批准了 {{deliverable.title}}。"],
      button: "打开项目",
    },
    "new-note": {
      name: "客户的新留言",
      subject: "{{client.contact_name}} 对 {{deliverable.title}} 的留言",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} 在 {{deliverable.title}} 上写了一条留言，就在审阅中他们查看的那个版本旁边。"],
      button: "打开审阅",
    },
    "client-says-paid": {
      name: "客户称已付款",
      subject: "{{client.contact_name}} 称已支付 {{invoice.number}}",
      lead: "{{invoice.number}} — {{invoice.title}}",
      paras: ["{{client.contact_name}} 称已于 {{invoice.client_paid_on.date}} 汇出 {{invoice.client_paid_amount}}。在我们有人核对银行并记录之前，不会记录任何付款。", "{{invoice.client_paid_note}}"],
      button: "记录付款",
    },
    "brief-sent": {
      name: "简报已发送",
      subject: "{{client.company}} 已发送简报",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} 已回答启动问题。答案在项目页面的“他们的简报”下。"],
      button: "打开项目",
    },
    "new-enquiry": {
      name: "新询价",
      subject: "来自 {{enquiry.name}} 的新询价",
      lead: "{{enquiry.number}} — {{enquiry.business}}",
      paras: ["{{enquiry.name}}通过你们网站上的表单来信。内容如下：", "{{enquiry.body}}"],
      button: "打开询价",
    },
  },
  "zh-TW": {
    greeting: "{{recipient.first_name}}，您好：",
    clientFoot: `${FOOT_TAIL} 直接回覆這封郵件，我們會有人讀到。`,
    studioFoot: "由 {{practice.name}} 寄至 {{practice.reply_to}}。在設定中更改我們通知您的內容。",
    "proposal-sent": {
      name: "提案已送出",
      subject: "給 {{client.company}} 的提案 — {{proposal.number}}",
      preheader: "{{proposal.title}} · {{proposal.total}}",
      paras: [
        "這是我們為 {{proposal.title}} 準備的提案：包含哪些內容、費用多少、如何付款。",
        "如果您滿意，請在入口網站輸入您的姓名接受並簽署。拒絕也完全正常，您可以在同一處告訴我們原因。",
      ],
      button: "閱讀 {{proposal.number}}",
    },
    "proposal-reminder": {
      name: "提案提醒",
      subject: "{{proposal.number}} 有效期至 {{proposal.valid_until.date}}",
      paras: ["簡單提醒一下，以免我們為 {{proposal.title}} 準備的提案被淹沒了。它的有效期至 {{proposal.valid_until.date}}。", "請在入口網站接受並簽署，或告訴我們怎樣才合適。"],
      button: "閱讀 {{proposal.number}}",
    },
    "new-work": {
      name: "新作品待審閱",
      subject: "有新作品可以查看 — {{project.name}}",
      paras: ["{{project.name}} 中有新作品可供您查看。", "請核准，或告訴我們需要修改什麼 — 兩者都很有幫助。"],
      button: "立即審閱",
    },
    handover: {
      name: "交接",
      subject: "{{project.name}} 的全部內容",
      paras: ["{{project.number}} 已完成。所有內容都在一個頁面上：設計稿、原始檔、字型，以及下次印刷時的注意事項。", "您可以把連結轉寄給印刷廠。開啟時不需要登入。"],
      button: "開啟交接頁",
    },
    "enquiry-reply": {
      name: "回覆詢價",
      subject: "回覆：您寄給 {{practice.name}} 的訊息",
      paras: ["感謝您與我們聯絡。", "我們能否在下週通話半小時？之後我們會給您一份簡短的提案，通常在幾天之內。"],
    },
    "ask-to-sign": {
      name: "請求簽署",
      subject: "{{proposal.number}} 有一項需要簽署",
      paras: ["您在我們使用入口網站之前接受了 {{proposal.title}}。能否在入口網站簽署？只需一分鐘：閱讀條款並輸入您的姓名。"],
      button: "閱讀並簽署",
    },
    "invoice-sent": {
      name: "發票已送出",
      subject: "來自 {{practice.name}} 的 {{invoice.number}} — {{invoice.total}}",
      preheader: "{{invoice.due_on.date}} 到期 · {{invoice.total}}",
      paras: ["這是 {{invoice.number}} — {{invoice.title}}。"],
      list: ["{{invoice.number}} · {{invoice.due_on.date}} 到期 · {{invoice.total}}"],
      box: { label: "付款方式", value: "{{addOn.invoices.payment_instructions}}" },
      reference: "付款備註：{{invoice.number}}",
      button: "查看 {{invoice.number}}",
    },
    "invoice-rung-1": {
      name: "第一次提醒",
      subject: "{{invoice.number}} — 以免您遺漏",
      paras: ["不必緊張 — {{invoice.number}} 已於 {{invoice.due_on.date}} 到期，我想款項還沒有入帳。如果已經在您的付款排程中，請忽略這封郵件。", "{{invoice.title}} 尚欠 {{invoice.balance}}。"],
      button: "查看 {{invoice.number}}",
    },
    "invoice-rung-2": {
      name: "第二次提醒",
      subject: "{{invoice.number}} 已逾期 {{invoice.due_on.days_since}} 天",
      paras: ["{{invoice.number}} 已逾期 {{invoice.due_on.days_since}} 天，尚欠 {{invoice.balance}}。能否告訴我何時付款，或者是否需要分兩次付？", "分期付款沒問題，也很容易安排。只有沉默才會讓事情尷尬。"],
      button: "查看 {{invoice.number}}",
    },
    "invoice-rung-3": {
      name: "第三次提醒",
      subject: "{{invoice.number}} 已逾期 {{invoice.due_on.days_since}} 天——結清前我們的工作暫停",
      paras: [
        "{{invoice.number}} 已逾期 {{invoice.due_on.days_since}} 天，尚欠 {{invoice.balance}}。根據您同意的條款第 6 條，從今天起我們為您進行中的工作將暫停，而不是繼續累積在一張未付的發票上。這並非針對個人。",
        "什麼都不會遺失。款項結清的那天，我們就從停下的地方繼續。",
      ],
      button: "查看 {{invoice.number}}",
    },
    "payment-receipt": {
      name: "收據",
      subject: "謝謝 — 我們已收到 {{payment.amount}}",
      paras: ["謝謝 — 我們已於 {{payment.paid_on.date}} 收到 {{invoice.number}} 的 {{payment.amount}}。"],
      list: ["{{payment.number}} · 用於 {{invoice.number}} · {{payment.amount}}", "剩餘金額 · {{invoice.due_on.date}} 到期 · {{invoice.balance}}"],
      button: "查看收據",
    },
    "accepted-and-signed": {
      name: "已接受並簽署",
      subject: "{{client.contact_name}} 已接受並簽署 {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.company}} 的 {{client.contact_name}} 輸入了姓名並在入口網站接受了提案。所同意的條款已固定在紀錄中。"],
      button: "開始專案",
    },
    declined: {
      name: "已拒絕",
      subject: "{{client.contact_name}} 拒絕了 {{proposal.number}}",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["{{client.company}} 的 {{client.contact_name}} 拒絕了提案。對方的說明：", "{{proposal.decline_note}}"],
      button: "開啟 {{proposal.number}}",
    },
    "asked-for-a-new-price": {
      name: "已請求新報價",
      subject: "{{client.contact_name}} 請求為 {{proposal.number}} 重新報價",
      lead: "{{proposal.number}} — {{proposal.title}}",
      paras: ["它的有效期至 {{proposal.valid_until.date}}。{{client.company}} 的 {{client.contact_name}} 希望得到新的報價。"],
      button: "開啟 {{proposal.number}}",
    },
    "changes-requested": {
      name: "已要求修改",
      subject: "{{client.contact_name}} 要求修改 {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} 退回了 {{deliverable.title}}。對方的說明：", "{{deliverable.review_note}}"],
      button: "開啟審閱",
    },
    approved: {
      name: "已核准",
      subject: "{{client.contact_name}} 核准了 {{deliverable.title}}",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} 於 {{deliverable.approved_on.date}} 在入口網站核准了 {{deliverable.title}}。"],
      button: "開啟專案",
    },
    "new-note": {
      name: "客戶的新留言",
      subject: "{{client.contact_name}} 對 {{deliverable.title}} 的留言",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} 在 {{deliverable.title}} 上寫了一則留言，就在審閱中他們查看的那個版本旁邊。"],
      button: "開啟審閱",
    },
    "client-says-paid": {
      name: "客戶稱已付款",
      subject: "{{client.contact_name}} 稱已支付 {{invoice.number}}",
      lead: "{{invoice.number}} — {{invoice.title}}",
      paras: ["{{client.contact_name}} 稱已於 {{invoice.client_paid_on.date}} 匯出 {{invoice.client_paid_amount}}。在我們有人核對銀行並記錄之前，不會記錄任何付款。", "{{invoice.client_paid_note}}"],
      button: "記錄付款",
    },
    "brief-sent": {
      name: "簡報已送出",
      subject: "{{client.company}} 已送出簡報",
      lead: "{{project.number}} — {{project.name}}",
      paras: ["{{client.contact_name}} 已回答啟動問題。答案在專案頁面的「他們的簡報」下。"],
      button: "開啟專案",
    },
    "new-enquiry": {
      name: "新詢價",
      subject: "來自 {{enquiry.name}} 的新詢價",
      lead: "{{enquiry.number}} — {{enquiry.business}}",
      paras: ["{{enquiry.name}}透過你們網站上的表單來信。內容如下：", "{{enquiry.body}}"],
      button: "開啟詢價",
    },
  },
};
