/**
 * The manifest's words in the seven languages beside English, keyed by the
 * English (see `labels.ts`). Every label the manifest shows is here.
 */
import type { Translation } from "./labels.ts";

export const WORDS: Record<string, Translation> = {
  "14 days": { "de-DE": "14 Tage", "fr-FR": "14 jours", "da-DK": "14 dage", "cs-CZ": "14 dní", "ar-EG": "14 يومًا", "zh-CN": "14 天", "zh-TW": "14 天" },
  "30 days": { "de-DE": "30 Tage", "fr-FR": "30 jours", "da-DK": "30 dage", "cs-CZ": "30 dní", "ar-EG": "30 يومًا", "zh-CN": "30 天", "zh-TW": "30 天" },
  "40 / 30 / 30": { "de-DE": "40 / 30 / 30", "fr-FR": "40 / 30 / 30", "da-DK": "40 / 30 / 30", "cs-CZ": "40 / 30 / 30", "ar-EG": "40 / 30 / 30", "zh-CN": "40 / 30 / 30", "zh-TW": "40 / 30 / 30" },
  "7 days": { "de-DE": "7 Tage", "fr-FR": "7 jours", "da-DK": "7 dage", "cs-CZ": "7 dní", "ar-EG": "7 أيام", "zh-CN": "7 天", "zh-TW": "7 天" },
  "A call": { "de-DE": "Ein Anruf", "fr-FR": "Un appel", "da-DK": "Et opkald", "cs-CZ": "Telefonát", "ar-EG": "مكالمة", "zh-CN": "电话", "zh-TW": "電話" },
  "A line": { "de-DE": "Eine Zeile", "fr-FR": "Une ligne", "da-DK": "En linje", "cs-CZ": "Jeden řádek", "ar-EG": "سطر واحد", "zh-CN": "一行", "zh-TW": "一行" },
  "A meeting": { "de-DE": "Ein Treffen", "fr-FR": "Une réunion", "da-DK": "Et møde", "cs-CZ": "Schůzka", "ar-EG": "اجتماع", "zh-CN": "会面", "zh-TW": "會面" },
  "A paragraph": { "de-DE": "Ein Absatz", "fr-FR": "Un paragraphe", "da-DK": "Et afsnit", "cs-CZ": "Odstavec", "ar-EG": "فقرة", "zh-CN": "一段", "zh-TW": "一段" },
  "Accepted": { "de-DE": "Angenommen", "fr-FR": "Accepté", "da-DK": "Accepteret", "cs-CZ": "Přijato", "ar-EG": "مقبول", "zh-CN": "已接受", "zh-TW": "已接受" },
  "Accepted and signed": { "de-DE": "Angenommen und unterschrieben", "fr-FR": "Accepté et signé", "da-DK": "Accepteret og underskrevet", "cs-CZ": "Přijato a podepsáno", "ar-EG": "قُبل ووُقّع", "zh-CN": "已接受并签署", "zh-TW": "已接受並簽署" },
  "Accepted by": { "de-DE": "Angenommen über", "fr-FR": "Accepté par", "da-DK": "Accepteret via", "cs-CZ": "Přijato přes", "ar-EG": "قُبل عبر", "zh-CN": "接受方式", "zh-TW": "接受方式" },
  "Action key": { "de-DE": "Aktionsschlüssel", "fr-FR": "Clé d’action", "da-DK": "Handlingsnøgle", "cs-CZ": "Klíč akce", "ar-EG": "مفتاح الإجراء", "zh-CN": "操作键", "zh-TW": "操作鍵" },
  "Active": { "de-DE": "Aktiv", "fr-FR": "Actif", "da-DK": "Aktiv", "cs-CZ": "Aktivní", "ar-EG": "نشط", "zh-CN": "进行中", "zh-TW": "進行中" },
  "Active projects": { "de-DE": "Aktive Projekte", "fr-FR": "Projets actifs", "da-DK": "Aktive projekter", "cs-CZ": "Aktivní projekty", "ar-EG": "المشاريع النشطة", "zh-CN": "进行中的项目", "zh-TW": "進行中的專案" },
  "Added": { "de-DE": "Neu", "fr-FR": "Ajoutée", "da-DK": "Tilføjet", "cs-CZ": "Přidáno", "ar-EG": "مضاف", "zh-CN": "新增", "zh-TW": "新增" },
  "Address": { "de-DE": "Adresse", "fr-FR": "Adresse", "da-DK": "Adresse", "cs-CZ": "Adresa", "ar-EG": "العنوان", "zh-CN": "地址", "zh-TW": "地址" },
  "Adminium user": { "de-DE": "Adminium-Benutzer", "fr-FR": "Utilisateur Adminium", "da-DK": "Adminium-bruger", "cs-CZ": "Uživatel Adminium", "ar-EG": "مستخدم Adminium", "zh-CN": "Adminium 用户", "zh-TW": "Adminium 使用者" },
  "All at the end": { "de-DE": "Alles am Ende", "fr-FR": "Tout à la fin", "da-DK": "Alt til sidst", "cs-CZ": "Vše na konci", "ar-EG": "الكل في النهاية", "zh-CN": "全部在结束时", "zh-TW": "全部在結束時" },
  "Amount": { "de-DE": "Betrag", "fr-FR": "Montant", "da-DK": "Beløb", "cs-CZ": "Částka", "ar-EG": "المبلغ", "zh-CN": "金额", "zh-TW": "金額" },
  "Amount off": { "de-DE": "Betrag abziehen", "fr-FR": "Montant déduit", "da-DK": "Beløb fratrukket", "cs-CZ": "Sleva v částce", "ar-EG": "خصم بمبلغ", "zh-CN": "减免金额", "zh-TW": "減免金額" },
  "Amount the client says they sent": { "de-DE": "Betrag laut Kunde überwiesen", "fr-FR": "Montant que le client dit avoir envoyé", "da-DK": "Beløb kunden siger, de har sendt", "cs-CZ": "Částka, kterou klient prý poslal", "ar-EG": "المبلغ الذي يقول العميل إنه أرسله", "zh-CN": "客户称已汇出的金额", "zh-TW": "客戶稱已匯出的金額" },
  "Answer": { "de-DE": "Antwort", "fr-FR": "Réponse", "da-DK": "Svar", "cs-CZ": "Odpověď", "ar-EG": "الإجابة", "zh-CN": "回答", "zh-TW": "回答" },
  "Approved": { "de-DE": "Freigegeben", "fr-FR": "Validé", "da-DK": "Godkendt", "cs-CZ": "Schváleno", "ar-EG": "معتمد", "zh-CN": "已批准", "zh-TW": "已核准" },
  "Approved by": { "de-DE": "Freigegeben über", "fr-FR": "Validé par", "da-DK": "Godkendt via", "cs-CZ": "Schváleno přes", "ar-EG": "اعتُمد عبر", "zh-CN": "批准方式", "zh-TW": "核准方式" },
  "Approved on": { "de-DE": "Freigegeben am", "fr-FR": "Validé le", "da-DK": "Godkendt den", "cs-CZ": "Schváleno dne", "ar-EG": "اعتُمد في", "zh-CN": "批准日期", "zh-TW": "核准日期" },
  "Ask to sign the terms": { "de-DE": "Bitte um Unterschrift der Bedingungen", "fr-FR": "Demande de signature des conditions", "da-DK": "Anmodning om at underskrive vilkårene", "cs-CZ": "Žádost o podpis podmínek", "ar-EG": "طلب توقيع الشروط", "zh-CN": "请求签署条款", "zh-TW": "請求簽署條款" },
  "Asked": { "de-DE": "Gefragt", "fr-FR": "Posée", "da-DK": "Stilles", "cs-CZ": "Klade se", "ar-EG": "مطروح", "zh-CN": "提问", "zh-TW": "提問" },
  "Asked for a new price": { "de-DE": "Neuer Preis angefragt", "fr-FR": "Nouveau prix demandé", "da-DK": "Bedt om en ny pris", "cs-CZ": "Žádost o novou cenu", "ar-EG": "طُلب سعر جديد", "zh-CN": "已请求新报价", "zh-TW": "已請求新報價" },
  "Bank transfer": { "de-DE": "Überweisung", "fr-FR": "Virement", "da-DK": "Bankoverførsel", "cs-CZ": "Bankovní převod", "ar-EG": "تحويل بنكي", "zh-CN": "银行转账", "zh-TW": "銀行轉帳" },
  "Being answered": { "de-DE": "Wird beantwortet", "fr-FR": "En cours de réponse", "da-DK": "Besvares", "cs-CZ": "Vyplňuje se", "ar-EG": "قيد الإجابة", "zh-CN": "填写中", "zh-TW": "填寫中" },
  "Brief": { "de-DE": "Briefing", "fr-FR": "Brief", "da-DK": "Brief", "cs-CZ": "Brief", "ar-EG": "الموجز", "zh-CN": "需求简报", "zh-TW": "需求簡報" },
  "Brief answer": { "de-DE": "Briefing-Antwort", "fr-FR": "Réponse au brief", "da-DK": "Svar på brief", "cs-CZ": "Odpověď v briefu", "ar-EG": "إجابة الموجز", "zh-CN": "简报回答", "zh-TW": "簡報回答" },
  "Brief answers": { "de-DE": "Briefing-Antworten", "fr-FR": "Réponses au brief", "da-DK": "Svar på brief", "cs-CZ": "Odpovědi v briefu", "ar-EG": "إجابات الموجز", "zh-CN": "简报回答", "zh-TW": "簡報回答" },
  "Brief question": { "de-DE": "Briefing-Frage", "fr-FR": "Question du brief", "da-DK": "Spørgsmål i brief", "cs-CZ": "Otázka v briefu", "ar-EG": "سؤال الموجز", "zh-CN": "简报问题", "zh-TW": "簡報問題" },
  "Brief questions": { "de-DE": "Briefing-Fragen", "fr-FR": "Questions du brief", "da-DK": "Spørgsmål i brief", "cs-CZ": "Otázky v briefu", "ar-EG": "أسئلة الموجز", "zh-CN": "简报问题", "zh-TW": "簡報問題" },
  "Brief sent": { "de-DE": "Briefing gesendet", "fr-FR": "Brief envoyé", "da-DK": "Brief sendt", "cs-CZ": "Brief odeslán", "ar-EG": "أُرسل الموجز", "zh-CN": "简报已发送", "zh-TW": "簡報已送出" },
  "Briefs": { "de-DE": "Briefings", "fr-FR": "Briefs", "da-DK": "Briefs", "cs-CZ": "Briefy", "ar-EG": "الموجزات", "zh-CN": "需求简报", "zh-TW": "需求簡報" },
  "Budget": { "de-DE": "Budget", "fr-FR": "Budget", "da-DK": "Budget", "cs-CZ": "Rozpočet", "ar-EG": "الميزانية", "zh-CN": "预算", "zh-TW": "預算" },
  "Business": { "de-DE": "Firma", "fr-FR": "Entreprise", "da-DK": "Virksomhed", "cs-CZ": "Firma", "ar-EG": "النشاط التجاري", "zh-CN": "商号", "zh-TW": "商號" },
  "By hand": { "de-DE": "Von Hand", "fr-FR": "À la main", "da-DK": "Manuelt", "cs-CZ": "Ručně", "ar-EG": "يدويًا", "zh-CN": "手动", "zh-TW": "手動" },
  "Card": { "de-DE": "Karte", "fr-FR": "Carte", "da-DK": "Kort", "cs-CZ": "Karta", "ar-EG": "بطاقة", "zh-CN": "银行卡", "zh-TW": "信用卡" },
  "Cash": { "de-DE": "Bar", "fr-FR": "Espèces", "da-DK": "Kontant", "cs-CZ": "Hotově", "ar-EG": "نقدًا", "zh-CN": "现金", "zh-TW": "現金" },
  "Change": { "de-DE": "Änderung", "fr-FR": "Changement", "da-DK": "Ændring", "cs-CZ": "Změna", "ar-EG": "التغيير", "zh-CN": "变更", "zh-TW": "變更" },
  "Changed": { "de-DE": "Geändert", "fr-FR": "Modifiée", "da-DK": "Ændret", "cs-CZ": "Změněno", "ar-EG": "معدّل", "zh-CN": "已修改", "zh-TW": "已修改" },
  "Changes asked": { "de-DE": "Änderungen erbeten", "fr-FR": "Modifications demandées", "da-DK": "Ændringer ønsket", "cs-CZ": "Požadovány změny", "ar-EG": "طُلبت تعديلات", "zh-CN": "已要求修改", "zh-TW": "已要求修改" },
  "Chase reminders to approve": { "de-DE": "Mahnungen zur Freigabe", "fr-FR": "Relances à valider", "da-DK": "Rykkere til godkendelse", "cs-CZ": "Upomínky ke schválení", "ar-EG": "تذكيرات تحصيل بانتظار الموافقة", "zh-CN": "待批准的催款提醒", "zh-TW": "待核准的催款提醒" },
  "Cheque": { "de-DE": "Scheck", "fr-FR": "Chèque", "da-DK": "Check", "cs-CZ": "Šek", "ar-EG": "شيك", "zh-CN": "支票", "zh-TW": "支票" },
  "Clause": { "de-DE": "Klausel", "fr-FR": "Clause", "da-DK": "Klausul", "cs-CZ": "Ustanovení", "ar-EG": "البند", "zh-CN": "条款", "zh-TW": "條款" },
  "Clauses": { "de-DE": "Klauseln", "fr-FR": "Clauses", "da-DK": "Klausuler", "cs-CZ": "Ustanovení", "ar-EG": "البنود", "zh-CN": "条款", "zh-TW": "條款" },
  "Client": { "de-DE": "Kunde", "fr-FR": "Client", "da-DK": "Kunde", "cs-CZ": "Klient", "ar-EG": "العميل", "zh-CN": "客户", "zh-TW": "客戶" },
  "Client note": { "de-DE": "Kundennotiz", "fr-FR": "Note client", "da-DK": "Kundenote", "cs-CZ": "Poznámka ke klientovi", "ar-EG": "ملاحظة عن العميل", "zh-CN": "客户备注", "zh-TW": "客戶備註" },
  "Client notes": { "de-DE": "Kundennotizen", "fr-FR": "Notes client", "da-DK": "Kundenoter", "cs-CZ": "Poznámky ke klientům", "ar-EG": "ملاحظات العملاء", "zh-CN": "客户备注", "zh-TW": "客戶備註" },
  "Client said so": { "de-DE": "Vom Kunden gemeldet", "fr-FR": "Signalé par le client", "da-DK": "Meldt af kunden", "cs-CZ": "Klient nahlásil", "ar-EG": "أبلغ العميل", "zh-CN": "客户告知时间", "zh-TW": "客戶告知時間" },
  "Client says paid": { "de-DE": "Kunde meldet Zahlung", "fr-FR": "Le client dit avoir payé", "da-DK": "Kunden siger betalt", "cs-CZ": "Klient uvádí, že zaplatil", "ar-EG": "العميل يقول إنه دفع", "zh-CN": "客户称已付款", "zh-TW": "客戶稱已付款" },
  "Clients": { "de-DE": "Kunden", "fr-FR": "Clients", "da-DK": "Kunder", "cs-CZ": "Klienti", "ar-EG": "العملاء", "zh-CN": "客户", "zh-TW": "客戶" },
  "Clients say they’ve paid": { "de-DE": "Kunden melden Zahlung", "fr-FR": "Clients qui disent avoir payé", "da-DK": "Kunder, der siger, de har betalt", "cs-CZ": "Klienti uvádějí, že zaplatili", "ar-EG": "عملاء يقولون إنهم دفعوا", "zh-CN": "客户称已付款", "zh-TW": "客戶稱已付款" },
  "Collected by month": { "de-DE": "Eingenommen nach Monat", "fr-FR": "Encaissé par mois", "da-DK": "Indbetalt pr. måned", "cs-CZ": "Přijato po měsících", "ar-EG": "المحصَّل حسب الشهر", "zh-CN": "按月收款", "zh-TW": "按月收款" },
  "Collected this month": { "de-DE": "Diesen Monat eingenommen", "fr-FR": "Encaissé ce mois-ci", "da-DK": "Indbetalt denne måned", "cs-CZ": "Přijato tento měsíc", "ar-EG": "المحصَّل هذا الشهر", "zh-CN": "本月已收款", "zh-TW": "本月已收款" },
  "Colour": { "de-DE": "Farbe", "fr-FR": "Couleur", "da-DK": "Farve", "cs-CZ": "Barva", "ar-EG": "اللون", "zh-CN": "颜色", "zh-TW": "顏色" },
  "Company": { "de-DE": "Firma", "fr-FR": "Société", "da-DK": "Firma", "cs-CZ": "Společnost", "ar-EG": "الشركة", "zh-CN": "公司", "zh-TW": "公司" },
  "Contact": { "de-DE": "Ansprechperson", "fr-FR": "Contact", "da-DK": "Kontaktperson", "cs-CZ": "Kontakt", "ar-EG": "جهة الاتصال", "zh-CN": "联系人", "zh-TW": "聯絡人" },
  "Created": { "de-DE": "Angelegt", "fr-FR": "Créé", "da-DK": "Oprettet", "cs-CZ": "Vytvořeno", "ar-EG": "أُنشئ", "zh-CN": "创建时间", "zh-TW": "建立時間" },
  "Currency": { "de-DE": "Währung", "fr-FR": "Devise", "da-DK": "Valuta", "cs-CZ": "Měna", "ar-EG": "العملة", "zh-CN": "货币", "zh-TW": "貨幣" },
  "Day the client says they paid": { "de-DE": "Zahltag laut Kunde", "fr-FR": "Jour où le client dit avoir payé", "da-DK": "Dag kunden siger, de betalte", "cs-CZ": "Den, kdy klient prý zaplatil", "ar-EG": "اليوم الذي يقول العميل إنه دفع فيه", "zh-CN": "客户称付款的日期", "zh-TW": "客戶稱付款的日期" },
  "Days a week": { "de-DE": "Tage pro Woche", "fr-FR": "Jours par semaine", "da-DK": "Dage om ugen", "cs-CZ": "Dnů v týdnu", "ar-EG": "أيام في الأسبوع", "zh-CN": "每周天数", "zh-TW": "每週天數" },
  "Days in a working week": { "de-DE": "Arbeitstage pro Woche", "fr-FR": "Jours dans une semaine de travail", "da-DK": "Dage i en arbejdsuge", "cs-CZ": "Dnů v pracovním týdnu", "ar-EG": "أيام أسبوع العمل", "zh-CN": "每周工作天数", "zh-TW": "每週工作天數" },
  "Decided": { "de-DE": "Entschieden", "fr-FR": "Décidé", "da-DK": "Afgjort", "cs-CZ": "Rozhodnuto", "ar-EG": "تقرّر", "zh-CN": "决定时间", "zh-TW": "決定時間" },
  "Declined": { "de-DE": "Abgelehnt", "fr-FR": "Refusé", "da-DK": "Afvist", "cs-CZ": "Odmítnuto", "ar-EG": "مرفوض", "zh-CN": "已拒绝", "zh-TW": "已拒絕" },
  "Deliverable": { "de-DE": "Lieferobjekt", "fr-FR": "Livrable", "da-DK": "Leverance", "cs-CZ": "Výstup", "ar-EG": "المُسلَّم", "zh-CN": "交付物", "zh-TW": "交付物" },
  "Deliverables": { "de-DE": "Lieferobjekte", "fr-FR": "Livrables", "da-DK": "Leverancer", "cs-CZ": "Výstupy", "ar-EG": "المُسلَّمات", "zh-CN": "交付物", "zh-TW": "交付物" },
  "Description": { "de-DE": "Beschreibung", "fr-FR": "Description", "da-DK": "Beskrivelse", "cs-CZ": "Popis", "ar-EG": "الوصف", "zh-CN": "描述", "zh-TW": "描述" },
  "Discount": { "de-DE": "Rabatt", "fr-FR": "Remise", "da-DK": "Rabat", "cs-CZ": "Sleva", "ar-EG": "الخصم", "zh-CN": "折扣", "zh-TW": "折扣" },
  "Discount kind": { "de-DE": "Rabattart", "fr-FR": "Type de remise", "da-DK": "Rabattype", "cs-CZ": "Druh slevy", "ar-EG": "نوع الخصم", "zh-CN": "折扣类型", "zh-TW": "折扣類型" },
  "Document": { "de-DE": "Dokument", "fr-FR": "Document", "da-DK": "Dokument", "cs-CZ": "Doklad", "ar-EG": "المستند", "zh-CN": "单据", "zh-TW": "單據" },
  "Done": { "de-DE": "Erledigt", "fr-FR": "Terminé", "da-DK": "Færdig", "cs-CZ": "Hotovo", "ar-EG": "مكتمل", "zh-CN": "已完成", "zh-TW": "已完成" },
  "Done this month": { "de-DE": "Diesen Monat abgeschlossen", "fr-FR": "Terminés ce mois-ci", "da-DK": "Færdige denne måned", "cs-CZ": "Dokončeno tento měsíc", "ar-EG": "اكتملت هذا الشهر", "zh-CN": "本月完成", "zh-TW": "本月完成" },
  "Draft": { "de-DE": "Entwurf", "fr-FR": "Brouillon", "da-DK": "Kladde", "cs-CZ": "Koncept", "ar-EG": "مسودة", "zh-CN": "草稿", "zh-TW": "草稿" },
  "Due": { "de-DE": "Fällig", "fr-FR": "Échéance", "da-DK": "Forfalder", "cs-CZ": "Splatnost", "ar-EG": "الموعد", "zh-CN": "到期", "zh-TW": "到期" },
  "Due on": { "de-DE": "Fällig am", "fr-FR": "Échéance le", "da-DK": "Forfalder den", "cs-CZ": "Splatné dne", "ar-EG": "تاريخ الاستحقاق", "zh-CN": "到期日", "zh-TW": "到期日" },
  "Email": { "de-DE": "E-Mail", "fr-FR": "E-mail", "da-DK": "E-mail", "cs-CZ": "E-mail", "ar-EG": "البريد الإلكتروني", "zh-CN": "邮箱", "zh-TW": "電子郵件" },
  "Emails": { "de-DE": "E-Mails", "fr-FR": "E-mails", "da-DK": "E-mails", "cs-CZ": "E-maily", "ar-EG": "رسائل البريد", "zh-CN": "邮件", "zh-TW": "郵件" },
  "Enquiries": { "de-DE": "Anfragen", "fr-FR": "Demandes", "da-DK": "Henvendelser", "cs-CZ": "Poptávky", "ar-EG": "الاستفسارات", "zh-CN": "询价", "zh-TW": "詢價" },
  "Enquiry": { "de-DE": "Anfrage", "fr-FR": "Demande", "da-DK": "Henvendelse", "cs-CZ": "Poptávka", "ar-EG": "الاستفسار", "zh-CN": "询价", "zh-TW": "詢價" },
  "Estimated days": { "de-DE": "Geschätzte Tage", "fr-FR": "Jours estimés", "da-DK": "Anslåede dage", "cs-CZ": "Odhad dnů", "ar-EG": "الأيام المقدّرة", "zh-CN": "预计天数", "zh-TW": "預估天數" },
  "File": { "de-DE": "Datei", "fr-FR": "Fichier", "da-DK": "Fil", "cs-CZ": "Soubor", "ar-EG": "الملف", "zh-CN": "文件", "zh-TW": "檔案" },
  "Files to review": { "de-DE": "Dateien zur Prüfung", "fr-FR": "Fichiers à valider", "da-DK": "Filer til gennemsyn", "cs-CZ": "Soubory ke kontrole", "ar-EG": "ملفات بانتظار المراجعة", "zh-CN": "待审阅的文件", "zh-TW": "待審閱的檔案" },
  "Fingerprint": { "de-DE": "Fingerabdruck", "fr-FR": "Empreinte", "da-DK": "Fingeraftryk", "cs-CZ": "Otisk", "ar-EG": "البصمة", "zh-CN": "指纹", "zh-TW": "指紋" },
  "Finished": { "de-DE": "Abgeschlossen", "fr-FR": "Terminé le", "da-DK": "Afsluttet", "cs-CZ": "Dokončeno", "ar-EG": "انتهى", "zh-CN": "完成日期", "zh-TW": "完成日期" },
  "Firm": { "de-DE": "Bestimmt", "fr-FR": "Ferme", "da-DK": "Bestemt", "cs-CZ": "Důrazné", "ar-EG": "حازم", "zh-CN": "严格", "zh-TW": "嚴格" },
  "First answer": { "de-DE": "Erste Antwort", "fr-FR": "Première réponse", "da-DK": "Første svar", "cs-CZ": "První odpověď", "ar-EG": "الإجابة الأولى", "zh-CN": "首次回答", "zh-TW": "首次回答" },
  "First reminder": { "de-DE": "Erste Erinnerung", "fr-FR": "Premier rappel", "da-DK": "Første påmindelse", "cs-CZ": "První připomínka", "ar-EG": "التذكير الأول", "zh-CN": "第一次提醒", "zh-TW": "第一次提醒" },
  "Fit": { "de-DE": "Passung", "fr-FR": "Adéquation", "da-DK": "Match", "cs-CZ": "Vhodnost", "ar-EG": "الملاءمة", "zh-CN": "匹配度", "zh-TW": "匹配度" },
  "Follow-up made": { "de-DE": "Folgeschritt ausgeführt", "fr-FR": "Suite donnée", "da-DK": "Opfølgning udført", "cs-CZ": "Navazující krok proveden", "ar-EG": "نُفّذت المتابعة", "zh-CN": "后续已执行", "zh-TW": "後續已執行" },
  "Font": { "de-DE": "Schrift", "fr-FR": "Police", "da-DK": "Skrifttype", "cs-CZ": "Písmo", "ar-EG": "الخط", "zh-CN": "字体", "zh-TW": "字型" },
  "Fonts": { "de-DE": "Schriften", "fr-FR": "Polices", "da-DK": "Skrifttyper", "cs-CZ": "Písma", "ar-EG": "الخطوط", "zh-CN": "字体", "zh-TW": "字型" },
  "From": { "de-DE": "Von", "fr-FR": "De la part de", "da-DK": "Fra", "cs-CZ": "Od", "ar-EG": "من", "zh-CN": "来自", "zh-TW": "來自" },
  "From the proposal": { "de-DE": "Aus dem Angebot", "fr-FR": "D’après la proposition", "da-DK": "Fra tilbuddet", "cs-CZ": "Z nabídky", "ar-EG": "من العرض", "zh-CN": "来自提案", "zh-TW": "來自提案" },
  "Gentle": { "de-DE": "Sanft", "fr-FR": "Doux", "da-DK": "Venlig", "cs-CZ": "Mírné", "ar-EG": "لطيف", "zh-CN": "温和", "zh-TW": "溫和" },
  "Going out": { "de-DE": "Wird gesendet", "fr-FR": "En cours d’envoi", "da-DK": "Sendes", "cs-CZ": "Odchází", "ar-EG": "قيد الإرسال", "zh-CN": "即将发送", "zh-TW": "即將寄出" },
  "Good fit": { "de-DE": "Passt gut", "fr-FR": "Bonne adéquation", "da-DK": "Godt match", "cs-CZ": "Dobře sedí", "ar-EG": "مناسب جدًا", "zh-CN": "很匹配", "zh-TW": "很匹配" },
  "Half now, half at handover": { "de-DE": "Hälfte jetzt, Hälfte bei Übergabe", "fr-FR": "Moitié maintenant, moitié à la livraison", "da-DK": "Halvdelen nu, halvdelen ved aflevering", "cs-CZ": "Polovina teď, polovina při předání", "ar-EG": "النصف الآن والنصف عند التسليم", "zh-CN": "现付一半，交付时付一半", "zh-TW": "現付一半，交付時付一半" },
  "Handover": { "de-DE": "Übergabe", "fr-FR": "Remise des fichiers", "da-DK": "Aflevering", "cs-CZ": "Předání", "ar-EG": "التسليم", "zh-CN": "交接", "zh-TW": "交接" },
  "Handover file": { "de-DE": "Übergabedatei", "fr-FR": "Fichier remis", "da-DK": "Afleveringsfil", "cs-CZ": "Předávaný soubor", "ar-EG": "ملف التسليم", "zh-CN": "交接文件", "zh-TW": "交接檔案" },
  "Handover files": { "de-DE": "Übergabedateien", "fr-FR": "Fichiers remis", "da-DK": "Afleveringsfiler", "cs-CZ": "Předávané soubory", "ar-EG": "ملفات التسليم", "zh-CN": "交接文件", "zh-TW": "交接檔案" },
  "Handover link code": { "de-DE": "Code des Übergabelinks", "fr-FR": "Code du lien de remise", "da-DK": "Kode til afleveringslink", "cs-CZ": "Kód odkazu k předání", "ar-EG": "رمز رابط التسليم", "zh-CN": "交接链接代码", "zh-TW": "交接連結代碼" },
  "Handover link expires": { "de-DE": "Übergabelink läuft ab", "fr-FR": "Expiration du lien de remise", "da-DK": "Afleveringslink udløber", "cs-CZ": "Platnost odkazu k předání", "ar-EG": "انتهاء رابط التسليم", "zh-CN": "交接链接到期", "zh-TW": "交接連結到期" },
  "Handover link stopped": { "de-DE": "Übergabelink gestoppt", "fr-FR": "Lien de remise arrêté", "da-DK": "Afleveringslink stoppet", "cs-CZ": "Odkaz k předání zastaven", "ar-EG": "أُوقف رابط التسليم", "zh-CN": "交接链接已停用", "zh-TW": "交接連結已停用" },
  "Handover link stopped on": { "de-DE": "Übergabelink gestoppt am", "fr-FR": "Lien de remise arrêté le", "da-DK": "Afleveringslink stoppet den", "cs-CZ": "Odkaz k předání zastaven dne", "ar-EG": "تاريخ إيقاف رابط التسليم", "zh-CN": "交接链接停用时间", "zh-TW": "交接連結停用時間" },
  "Handover notes": { "de-DE": "Übergabenotizen", "fr-FR": "Notes de remise", "da-DK": "Afleveringsnoter", "cs-CZ": "Poznámky k předání", "ar-EG": "ملاحظات التسليم", "zh-CN": "交接说明", "zh-TW": "交接說明" },
  "Handover sent": { "de-DE": "Übergabe gesendet", "fr-FR": "Remise envoyée", "da-DK": "Aflevering sendt", "cs-CZ": "Předání odesláno", "ar-EG": "أُرسل التسليم", "zh-CN": "交接已发送", "zh-TW": "交接已送出" },
  "Handover sent on": { "de-DE": "Übergabe gesendet am", "fr-FR": "Remise envoyée le", "da-DK": "Aflevering sendt den", "cs-CZ": "Předání odesláno dne", "ar-EG": "تاريخ إرسال التسليم", "zh-CN": "交接发送时间", "zh-TW": "交接送出時間" },
  "Hint": { "de-DE": "Hinweis", "fr-FR": "Indication", "da-DK": "Tip", "cs-CZ": "Nápověda", "ar-EG": "تلميح", "zh-CN": "提示", "zh-TW": "提示" },
  "Holds until": { "de-DE": "Gültig bis", "fr-FR": "Valable jusqu’au", "da-DK": "Gælder til", "cs-CZ": "Platí do", "ar-EG": "صالح حتى", "zh-CN": "有效期至", "zh-TW": "有效期至" },
  "Hours in a working day": { "de-DE": "Stunden pro Arbeitstag", "fr-FR": "Heures dans une journée de travail", "da-DK": "Timer i en arbejdsdag", "cs-CZ": "Hodin v pracovním dni", "ar-EG": "ساعات يوم العمل", "zh-CN": "每个工作日的小时数", "zh-TW": "每個工作日的時數" },
  "Hours it stands for": { "de-DE": "Entsprechende Stunden", "fr-FR": "Heures correspondantes", "da-DK": "Timer det svarer til", "cs-CZ": "Odpovídající hodiny", "ar-EG": "الساعات التي يمثلها", "zh-CN": "对应小时数", "zh-TW": "對應時數" },
  "How it is paid": { "de-DE": "Zahlungsaufteilung", "fr-FR": "Échéancier", "da-DK": "Betalingsfordeling", "cs-CZ": "Rozvržení plateb", "ar-EG": "طريقة الدفع", "zh-CN": "付款方式", "zh-TW": "付款方式" },
  "How they found us": { "de-DE": "Wie sie uns gefunden haben", "fr-FR": "Comment ils nous ont trouvés", "da-DK": "Hvordan de fandt os", "cs-CZ": "Jak nás našli", "ar-EG": "كيف وجدونا", "zh-CN": "从何得知我们", "zh-TW": "從何得知我們" },
  "How we sign off": { "de-DE": "Unser Gruß", "fr-FR": "Notre formule de fin", "da-DK": "Vores hilsen", "cs-CZ": "Jak se podepisujeme", "ar-EG": "طريقة ختامنا", "zh-CN": "落款", "zh-TW": "落款" },
  "Icon": { "de-DE": "Symbol", "fr-FR": "Icône", "da-DK": "Ikon", "cs-CZ": "Ikona", "ar-EG": "الأيقونة", "zh-CN": "图标", "zh-TW": "圖示" },
  "In force": { "de-DE": "In Kraft", "fr-FR": "En vigueur", "da-DK": "Gældende", "cs-CZ": "Platné", "ar-EG": "سارية", "zh-CN": "生效中", "zh-TW": "生效中" },
  "In force from": { "de-DE": "In Kraft seit", "fr-FR": "En vigueur depuis", "da-DK": "Gældende fra", "cs-CZ": "Platné od", "ar-EG": "سارية من", "zh-CN": "生效日期", "zh-TW": "生效日期" },
  "In use": { "de-DE": "In Verwendung", "fr-FR": "Utilisé", "da-DK": "I brug", "cs-CZ": "Používá se", "ar-EG": "قيد الاستخدام", "zh-CN": "使用中", "zh-TW": "使用中" },
  "Initials": { "de-DE": "Initialen", "fr-FR": "Initiales", "da-DK": "Initialer", "cs-CZ": "Iniciály", "ar-EG": "الأحرف الأولى", "zh-CN": "姓名缩写", "zh-TW": "姓名縮寫" },
  "Invoice": { "de-DE": "Rechnung", "fr-FR": "Facture", "da-DK": "Faktura", "cs-CZ": "Faktura", "ar-EG": "الفاتورة", "zh-CN": "发票", "zh-TW": "發票" },
  "Invoice line": { "de-DE": "Rechnungsposition", "fr-FR": "Ligne de facture", "da-DK": "Fakturalinje", "cs-CZ": "Položka faktury", "ar-EG": "بند الفاتورة", "zh-CN": "发票明细", "zh-TW": "發票明細" },
  "Invoice lines": { "de-DE": "Rechnungspositionen", "fr-FR": "Lignes de facture", "da-DK": "Fakturalinjer", "cs-CZ": "Položky faktury", "ar-EG": "بنود الفواتير", "zh-CN": "发票明细", "zh-TW": "發票明細" },
  "Invoice sent": { "de-DE": "Rechnung gesendet", "fr-FR": "Facture envoyée", "da-DK": "Faktura sendt", "cs-CZ": "Faktura odeslána", "ar-EG": "أُرسلت الفاتورة", "zh-CN": "发票已发送", "zh-TW": "發票已送出" },
  "Invoiced by month": { "de-DE": "In Rechnung gestellt nach Monat", "fr-FR": "Facturé par mois", "da-DK": "Faktureret pr. måned", "cs-CZ": "Fakturováno po měsících", "ar-EG": "المُفوتَر حسب الشهر", "zh-CN": "按月开票", "zh-TW": "按月開立發票" },
  "Invoices": { "de-DE": "Rechnungen", "fr-FR": "Factures", "da-DK": "Fakturaer", "cs-CZ": "Faktury", "ar-EG": "الفواتير", "zh-CN": "发票", "zh-TW": "發票" },
  "Invoices falling due next": { "de-DE": "Als Nächstes fällige Rechnungen", "fr-FR": "Prochaines factures à échéance", "da-DK": "Fakturaer, der forfalder næste gang", "cs-CZ": "Faktury splatné jako další", "ar-EG": "الفواتير المستحقة تاليًا", "zh-CN": "即将到期的发票", "zh-TW": "即將到期的發票" },
  "Issued on": { "de-DE": "Ausgestellt am", "fr-FR": "Émise le", "da-DK": "Udstedt den", "cs-CZ": "Vystaveno dne", "ar-EG": "تاريخ الإصدار", "zh-CN": "开具日期", "zh-TW": "開立日期" },
  "Key": { "de-DE": "Schlüssel", "fr-FR": "Clé", "da-DK": "Nøgle", "cs-CZ": "Klíč", "ar-EG": "المفتاح", "zh-CN": "键", "zh-TW": "鍵" },
  "Kind": { "de-DE": "Art", "fr-FR": "Type", "da-DK": "Type", "cs-CZ": "Druh", "ar-EG": "النوع", "zh-CN": "类型", "zh-TW": "類型" },
  "Language": { "de-DE": "Sprache", "fr-FR": "Langue", "da-DK": "Sprog", "cs-CZ": "Jazyk", "ar-EG": "اللغة", "zh-CN": "语言", "zh-TW": "語言" },
  "Licence": { "de-DE": "Lizenz", "fr-FR": "Licence", "da-DK": "Licens", "cs-CZ": "Licence", "ar-EG": "الترخيص", "zh-CN": "授权", "zh-TW": "授權" },
  "Link": { "de-DE": "Link", "fr-FR": "Lien", "da-DK": "Link", "cs-CZ": "Odkaz", "ar-EG": "الرابط", "zh-CN": "链接", "zh-TW": "連結" },
  "Manage": { "de-DE": "Verwalten", "fr-FR": "Gérer", "da-DK": "Administrer", "cs-CZ": "Správa", "ar-EG": "الإدارة", "zh-CN": "管理", "zh-TW": "管理" },
  "Marked approved by": { "de-DE": "Als freigegeben markiert von", "fr-FR": "Marqué validé par", "da-DK": "Markeret godkendt af", "cs-CZ": "Označil jako schválené", "ar-EG": "وسمه معتمدًا", "zh-CN": "标记批准者", "zh-TW": "標記核准者" },
  "Maybe": { "de-DE": "Vielleicht", "fr-FR": "Peut-être", "da-DK": "Måske", "cs-CZ": "Možná", "ar-EG": "ربما", "zh-CN": "也许", "zh-TW": "也許" },
  "Milestone": { "de-DE": "Meilenstein", "fr-FR": "Étape", "da-DK": "Milepæl", "cs-CZ": "Milník", "ar-EG": "المرحلة", "zh-CN": "里程碑", "zh-TW": "里程碑" },
  "Milestones": { "de-DE": "Meilensteine", "fr-FR": "Étapes", "da-DK": "Milepæle", "cs-CZ": "Milníky", "ar-EG": "المراحل", "zh-CN": "里程碑", "zh-TW": "里程碑" },
  "Milestones this week": { "de-DE": "Meilensteine diese Woche", "fr-FR": "Étapes de la semaine", "da-DK": "Milepæle denne uge", "cs-CZ": "Milníky tento týden", "ar-EG": "مراحل هذا الأسبوع", "zh-CN": "本周里程碑", "zh-TW": "本週里程碑" },
  "Name": { "de-DE": "Name", "fr-FR": "Nom", "da-DK": "Navn", "cs-CZ": "Jméno", "ar-EG": "الاسم", "zh-CN": "名称", "zh-TW": "名稱" },
  "New": { "de-DE": "Neu", "fr-FR": "Nouvelle", "da-DK": "Ny", "cs-CZ": "Nová", "ar-EG": "جديد", "zh-CN": "新", "zh-TW": "新" },
  "New enquiries": { "de-DE": "Neue Anfragen", "fr-FR": "Nouvelles demandes", "da-DK": "Nye henvendelser", "cs-CZ": "Nové poptávky", "ar-EG": "استفسارات جديدة", "zh-CN": "新询价", "zh-TW": "新詢價" },
  "New note from a client": { "de-DE": "Neue Notiz eines Kunden", "fr-FR": "Nouvelle note d’un client", "da-DK": "Ny note fra en kunde", "cs-CZ": "Nová poznámka od klienta", "ar-EG": "ملاحظة جديدة من عميل", "zh-CN": "客户的新留言", "zh-TW": "客戶的新留言" },
  "New price asked": { "de-DE": "Neuer Preis angefragt am", "fr-FR": "Nouveau prix demandé le", "da-DK": "Ny pris ønsket den", "cs-CZ": "Nová cena vyžádána", "ar-EG": "تاريخ طلب السعر الجديد", "zh-CN": "请求新报价时间", "zh-TW": "請求新報價時間" },
  "New work to review": { "de-DE": "Neue Arbeit zur Durchsicht", "fr-FR": "Nouveau travail à relire", "da-DK": "Nyt arbejde til gennemsyn", "cs-CZ": "Nová práce ke kontrole", "ar-EG": "عمل جديد للمراجعة", "zh-CN": "新作品待审阅", "zh-TW": "新作品待審閱" },
  "Next": { "de-DE": "Als Nächstes", "fr-FR": "À venir", "da-DK": "Næste", "cs-CZ": "Další", "ar-EG": "التالي", "zh-CN": "下一步", "zh-TW": "下一步" },
  "No longer needed": { "de-DE": "Nicht mehr nötig", "fr-FR": "Plus nécessaire", "da-DK": "Ikke længere nødvendig", "cs-CZ": "Už není potřeba", "ar-EG": "لم يعد مطلوبًا", "zh-CN": "不再需要", "zh-TW": "不再需要" },
  "Not for us": { "de-DE": "Nichts für uns", "fr-FR": "Pas pour nous", "da-DK": "Ikke noget for os", "cs-CZ": "Není pro nás", "ar-EG": "ليس لنا", "zh-CN": "不适合我们", "zh-TW": "不適合我們" },
  "Not sent": { "de-DE": "Nicht gesendet", "fr-FR": "Non envoyé", "da-DK": "Ikke sendt", "cs-CZ": "Neodesláno", "ar-EG": "لم يُرسل", "zh-CN": "未发送", "zh-TW": "未送出" },
  "Not shared": { "de-DE": "Nicht geteilt", "fr-FR": "Non partagé", "da-DK": "Ikke delt", "cs-CZ": "Nesdíleno", "ar-EG": "غير مشارك", "zh-CN": "未共享", "zh-TW": "未分享" },
  "Note": { "de-DE": "Notiz", "fr-FR": "Note", "da-DK": "Note", "cs-CZ": "Poznámka", "ar-EG": "ملاحظة", "zh-CN": "备注", "zh-TW": "備註" },
  "Now": { "de-DE": "Jetzt", "fr-FR": "En cours", "da-DK": "Nu", "cs-CZ": "Teď", "ar-EG": "الآن", "zh-CN": "进行中", "zh-TW": "進行中" },
  "Number": { "de-DE": "Nummer", "fr-FR": "Numéro", "da-DK": "Nummer", "cs-CZ": "Číslo", "ar-EG": "الرقم", "zh-CN": "编号", "zh-TW": "編號" },
  "Number in the series": { "de-DE": "Laufende Nummer", "fr-FR": "Numéro dans la série", "da-DK": "Nummer i rækken", "cs-CZ": "Pořadové číslo", "ar-EG": "الرقم في السلسلة", "zh-CN": "序列号", "zh-TW": "序號" },
  "On receipt": { "de-DE": "Bei Erhalt", "fr-FR": "À réception", "da-DK": "Ved modtagelse", "cs-CZ": "Při obdržení", "ar-EG": "عند الاستلام", "zh-CN": "收到即付", "zh-TW": "收到即付" },
  "Open the desk": { "de-DE": "Studio-Arbeitsplatz öffnen", "fr-FR": "Ouvrir le bureau du studio", "da-DK": "Åbn studiets skrivebord", "cs-CZ": "Otevřít pracoviště studia", "ar-EG": "افتح مكتب الاستوديو", "zh-CN": "打开工作室工作台", "zh-TW": "開啟工作室工作台" },
  "Other": { "de-DE": "Andere", "fr-FR": "Autre", "da-DK": "Andet", "cs-CZ": "Jiné", "ar-EG": "أخرى", "zh-CN": "其他", "zh-TW": "其他" },
  "Outstanding": { "de-DE": "Offen", "fr-FR": "À encaisser", "da-DK": "Udestående", "cs-CZ": "Nezaplaceno", "ar-EG": "المستحق", "zh-CN": "未收款", "zh-TW": "未收款" },
  "Overdue": { "de-DE": "Überfällig", "fr-FR": "En retard", "da-DK": "Forfalden", "cs-CZ": "Po splatnosti", "ar-EG": "المتأخر", "zh-CN": "已逾期", "zh-TW": "已逾期" },
  "Overdue invoices": { "de-DE": "Überfällige Rechnungen", "fr-FR": "Factures en retard", "da-DK": "Forfaldne fakturaer", "cs-CZ": "Faktury po splatnosti", "ar-EG": "الفواتير المتأخرة", "zh-CN": "逾期发票", "zh-TW": "逾期發票" },
  "Overtaken": { "de-DE": "Überholt", "fr-FR": "Remplacé", "da-DK": "Overhalet", "cs-CZ": "Nahrazeno", "ar-EG": "تجاوزه تذكير لاحق", "zh-CN": "已被后续取代", "zh-TW": "已被後續取代" },
  "Overview": { "de-DE": "Übersicht", "fr-FR": "Vue d’ensemble", "da-DK": "Overblik", "cs-CZ": "Přehled", "ar-EG": "نظرة عامة", "zh-CN": "概览", "zh-TW": "總覽" },
  "Owed · 1–30 days late": { "de-DE": "Offen · 1–30 Tage überfällig", "fr-FR": "Dû · 1 à 30 jours de retard", "da-DK": "Udestående · 1–30 dage for sent", "cs-CZ": "Dlužno · 1–30 dní po splatnosti", "ar-EG": "المستحق · متأخر 1–30 يومًا", "zh-CN": "应收 · 逾期 1–30 天", "zh-TW": "應收 · 逾期 1–30 天" },
  "Owed · 31–60 days late": { "de-DE": "Offen · 31–60 Tage überfällig", "fr-FR": "Dû · 31 à 60 jours de retard", "da-DK": "Udestående · 31–60 dage for sent", "cs-CZ": "Dlužno · 31–60 dní po splatnosti", "ar-EG": "المستحق · متأخر 31–60 يومًا", "zh-CN": "应收 · 逾期 31–60 天", "zh-TW": "應收 · 逾期 31–60 天" },
  "Owed · not yet due": { "de-DE": "Offen · noch nicht fällig", "fr-FR": "Dû · pas encore échu", "da-DK": "Udestående · ikke forfaldent endnu", "cs-CZ": "Dlužno · zatím nesplatné", "ar-EG": "المستحق · لم يحن موعده", "zh-CN": "应收 · 尚未到期", "zh-TW": "應收 · 尚未到期" },
  "Owed · over 60 days late": { "de-DE": "Offen · über 60 Tage überfällig", "fr-FR": "Dû · plus de 60 jours de retard", "da-DK": "Udestående · over 60 dage for sent", "cs-CZ": "Dlužno · přes 60 dní po splatnosti", "ar-EG": "المستحق · متأخر أكثر من 60 يومًا", "zh-CN": "应收 · 逾期超过 60 天", "zh-TW": "應收 · 逾期超過 60 天" },
  "Paid": { "de-DE": "Bezahlt", "fr-FR": "Payé", "da-DK": "Betalt", "cs-CZ": "Zaplaceno", "ar-EG": "المدفوع", "zh-CN": "已付", "zh-TW": "已付" },
  "Paid by": { "de-DE": "Bezahlt per", "fr-FR": "Payé par", "da-DK": "Betalt med", "cs-CZ": "Zaplaceno přes", "ar-EG": "طريقة الدفع", "zh-CN": "付款方式", "zh-TW": "付款方式" },
  "Paid on": { "de-DE": "Bezahlt am", "fr-FR": "Payé le", "da-DK": "Betalt den", "cs-CZ": "Zaplaceno dne", "ar-EG": "تاريخ الدفع", "zh-CN": "付款日期", "zh-TW": "付款日期" },
  "Paid, project still paused": { "de-DE": "Bezahlt, Projekt noch pausiert", "fr-FR": "Payé, projet toujours en pause", "da-DK": "Betalt, projektet stadig sat på pause", "cs-CZ": "Zaplaceno, projekt stále pozastaven", "ar-EG": "دُفع والمشروع ما زال متوقفًا", "zh-CN": "已付款，项目仍暂停", "zh-TW": "已付款，專案仍暫停" },
  "Parked": { "de-DE": "Zurückgestellt", "fr-FR": "En attente", "da-DK": "Parkeret", "cs-CZ": "Odloženo", "ar-EG": "مؤجَّل", "zh-CN": "搁置", "zh-TW": "擱置" },
  "Parked until": { "de-DE": "Zurückgestellt bis", "fr-FR": "En attente jusqu’au", "da-DK": "Parkeret til", "cs-CZ": "Odloženo do", "ar-EG": "مؤجَّل حتى", "zh-CN": "搁置至", "zh-TW": "擱置至" },
  "Paused": { "de-DE": "Pausiert", "fr-FR": "En pause", "da-DK": "Sat på pause", "cs-CZ": "Pozastaveno", "ar-EG": "متوقف مؤقتًا", "zh-CN": "已暂停", "zh-TW": "已暫停" },
  "Payment": { "de-DE": "Zahlung", "fr-FR": "Paiement", "da-DK": "Betaling", "cs-CZ": "Platba", "ar-EG": "الدفعة", "zh-CN": "付款", "zh-TW": "付款" },
  "Payment note": { "de-DE": "Zahlungsnotiz", "fr-FR": "Note de paiement", "da-DK": "Betalingsnote", "cs-CZ": "Poznámka k platbě", "ar-EG": "ملاحظة الدفع", "zh-CN": "付款备注", "zh-TW": "付款備註" },
  "Payment terms": { "de-DE": "Zahlungsziel", "fr-FR": "Conditions de paiement", "da-DK": "Betalingsbetingelser", "cs-CZ": "Splatnost", "ar-EG": "شروط الدفع", "zh-CN": "付款期限", "zh-TW": "付款期限" },
  "Payments": { "de-DE": "Zahlungen", "fr-FR": "Paiements", "da-DK": "Betalinger", "cs-CZ": "Platby", "ar-EG": "المدفوعات", "zh-CN": "付款记录", "zh-TW": "付款紀錄" },
  "People": { "de-DE": "Team", "fr-FR": "Équipe", "da-DK": "Personer", "cs-CZ": "Lidé", "ar-EG": "الفريق", "zh-CN": "成员", "zh-TW": "成員" },
  "Percent off": { "de-DE": "Prozent abziehen", "fr-FR": "Pourcentage déduit", "da-DK": "Procent fratrukket", "cs-CZ": "Sleva v procentech", "ar-EG": "خصم بنسبة", "zh-CN": "减免百分比", "zh-TW": "減免百分比" },
  "Person": { "de-DE": "Person", "fr-FR": "Personne", "da-DK": "Person", "cs-CZ": "Osoba", "ar-EG": "الشخص", "zh-CN": "成员", "zh-TW": "成員" },
  "Phone": { "de-DE": "Telefon", "fr-FR": "Téléphone", "da-DK": "Telefon", "cs-CZ": "Telefon", "ar-EG": "الهاتف", "zh-CN": "电话", "zh-TW": "電話" },
  "Pin across": { "de-DE": "Markierung waagerecht", "fr-FR": "Repère horizontal", "da-DK": "Markør vandret", "cs-CZ": "Značka vodorovně", "ar-EG": "الدبوس أفقيًا", "zh-CN": "标记横向位置", "zh-TW": "標記橫向位置" },
  "Pin down": { "de-DE": "Markierung senkrecht", "fr-FR": "Repère vertical", "da-DK": "Markør lodret", "cs-CZ": "Značka svisle", "ar-EG": "الدبوس رأسيًا", "zh-CN": "标记纵向位置", "zh-TW": "標記縱向位置" },
  "Position": { "de-DE": "Reihenfolge", "fr-FR": "Ordre", "da-DK": "Rækkefølge", "cs-CZ": "Pořadí", "ar-EG": "الترتيب", "zh-CN": "顺序", "zh-TW": "順序" },
  "Posted": { "de-DE": "Hochgeladen", "fr-FR": "Publié", "da-DK": "Lagt op", "cs-CZ": "Nahráno", "ar-EG": "نُشر", "zh-CN": "发布时间", "zh-TW": "發布時間" },
  "Posted by": { "de-DE": "Hochgeladen von", "fr-FR": "Publié par", "da-DK": "Lagt op af", "cs-CZ": "Nahrál", "ar-EG": "نشره", "zh-CN": "发布者", "zh-TW": "發布者" },
  "Project": { "de-DE": "Projekt", "fr-FR": "Projet", "da-DK": "Projekt", "cs-CZ": "Projekt", "ar-EG": "المشروع", "zh-CN": "项目", "zh-TW": "專案" },
  "Projects": { "de-DE": "Projekte", "fr-FR": "Projets", "da-DK": "Projekter", "cs-CZ": "Projekty", "ar-EG": "المشاريع", "zh-CN": "项目", "zh-TW": "專案" },
  "Proposal": { "de-DE": "Angebot", "fr-FR": "Proposition", "da-DK": "Tilbud", "cs-CZ": "Nabídka", "ar-EG": "العرض", "zh-CN": "提案", "zh-TW": "提案" },
  "Proposal line": { "de-DE": "Angebotsposition", "fr-FR": "Ligne de proposition", "da-DK": "Tilbudslinje", "cs-CZ": "Položka nabídky", "ar-EG": "بند العرض", "zh-CN": "提案明细", "zh-TW": "提案明細" },
  "Proposal lines": { "de-DE": "Angebotspositionen", "fr-FR": "Lignes de proposition", "da-DK": "Tilbudslinjer", "cs-CZ": "Položky nabídek", "ar-EG": "بنود العروض", "zh-CN": "提案明细", "zh-TW": "提案明細" },
  "Proposal reminder": { "de-DE": "Erinnerung an ein Angebot", "fr-FR": "Rappel de proposition", "da-DK": "Påmindelse om tilbud", "cs-CZ": "Připomínka nabídky", "ar-EG": "تذكير بالعرض", "zh-CN": "提案提醒", "zh-TW": "提案提醒" },
  "Proposal sent": { "de-DE": "Angebot gesendet", "fr-FR": "Proposition envoyée", "da-DK": "Tilbud sendt", "cs-CZ": "Nabídka odeslána", "ar-EG": "أُرسل العرض", "zh-CN": "提案已发送", "zh-TW": "提案已送出" },
  "Proposals": { "de-DE": "Angebote", "fr-FR": "Propositions", "da-DK": "Tilbud", "cs-CZ": "Nabídky", "ar-EG": "العروض", "zh-CN": "提案", "zh-TW": "提案" },
  "Proposals sent": { "de-DE": "Versendete Angebote", "fr-FR": "Propositions envoyées", "da-DK": "Sendte tilbud", "cs-CZ": "Odeslané nabídky", "ar-EG": "العروض المُرسلة", "zh-CN": "已发送的提案", "zh-TW": "已送出的提案" },
  "Proposals waiting": { "de-DE": "Offene Angebote", "fr-FR": "Propositions en attente", "da-DK": "Tilbud, der venter", "cs-CZ": "Čekající nabídky", "ar-EG": "عروض بانتظار الرد", "zh-CN": "待回复的提案", "zh-TW": "待回覆的提案" },
  "Proposals, invoices, receipts and payment reminders are made by this add-on.": { "de-DE": "Angebote, Rechnungen, Quittungen und Zahlungserinnerungen macht dieses Add-on.", "fr-FR": "Les propositions, factures, reçus et relances de paiement sont faits par ce module.", "da-DK": "Tilbud, fakturaer, kvitteringer og betalingspåmindelser laves af denne tilføjelse.", "cs-CZ": "Nabídky, faktury, potvrzení a upomínky plateb vytváří tento doplněk.", "ar-EG": "يُنشئ هذا الملحق العروض والفواتير والإيصالات وتذكيرات الدفع.", "zh-CN": "提案、发票、收据和付款提醒由此插件生成。", "zh-TW": "提案、發票、收據和付款提醒由此外掛產生。" },
  "Quantity": { "de-DE": "Menge", "fr-FR": "Quantité", "da-DK": "Antal", "cs-CZ": "Množství", "ar-EG": "الكمية", "zh-CN": "数量", "zh-TW": "數量" },
  "Question": { "de-DE": "Frage", "fr-FR": "Question", "da-DK": "Spørgsmål", "cs-CZ": "Otázka", "ar-EG": "السؤال", "zh-CN": "问题", "zh-TW": "問題" },
  "Rate": { "de-DE": "Satz", "fr-FR": "Tarif", "da-DK": "Sats", "cs-CZ": "Sazba", "ar-EG": "السعر", "zh-CN": "单价", "zh-TW": "單價" },
  "Rate card": { "de-DE": "Preisliste", "fr-FR": "Liste des tarifs", "da-DK": "Prisliste", "cs-CZ": "Ceník", "ar-EG": "قائمة الأسعار", "zh-CN": "价目表", "zh-TW": "價目表" },
  "Receipt": { "de-DE": "Quittung", "fr-FR": "Reçu", "da-DK": "Kvittering", "cs-CZ": "Potvrzení o platbě", "ar-EG": "الإيصال", "zh-CN": "收据", "zh-TW": "收據" },
  "Receipt number": { "de-DE": "Quittungsnummer", "fr-FR": "Numéro du reçu", "da-DK": "Kvitteringsnummer", "cs-CZ": "Číslo potvrzení", "ar-EG": "رقم الإيصال", "zh-CN": "收据编号", "zh-TW": "收據編號" },
  "Received": { "de-DE": "Eingegangen", "fr-FR": "Reçue", "da-DK": "Modtaget", "cs-CZ": "Přijato", "ar-EG": "تاريخ الاستلام", "zh-CN": "收到时间", "zh-TW": "收到時間" },
  "Recorded": { "de-DE": "Erfasst", "fr-FR": "Enregistré", "da-DK": "Registreret", "cs-CZ": "Zaznamenáno", "ar-EG": "سُجّل", "zh-CN": "记录时间", "zh-TW": "記錄時間" },
  "Recorded by": { "de-DE": "Erfasst von", "fr-FR": "Enregistré par", "da-DK": "Registreret af", "cs-CZ": "Zaznamenal", "ar-EG": "سجّله", "zh-CN": "记录人", "zh-TW": "記錄人" },
  "Records": { "de-DE": "Aufzeichnungen", "fr-FR": "Registres", "da-DK": "Registreringer", "cs-CZ": "Záznamy", "ar-EG": "السجلات", "zh-CN": "记录", "zh-TW": "記錄" },
  "Reminders": { "de-DE": "Erinnerungen", "fr-FR": "Relances", "da-DK": "Påmindelser", "cs-CZ": "Upomínky", "ar-EG": "التذكيرات", "zh-CN": "提醒", "zh-TW": "提醒" },
  "Replied": { "de-DE": "Beantwortet", "fr-FR": "Répondu", "da-DK": "Besvaret", "cs-CZ": "Zodpovězeno", "ar-EG": "تم الرد", "zh-CN": "已回复", "zh-TW": "已回覆" },
  "Reply to an enquiry": { "de-DE": "Antwort auf eine Anfrage", "fr-FR": "Réponse à une demande", "da-DK": "Svar på en henvendelse", "cs-CZ": "Odpověď na poptávku", "ar-EG": "رد على استفسار", "zh-CN": "回复询价", "zh-TW": "回覆詢價" },
  "Reply-to address": { "de-DE": "Antwortadresse", "fr-FR": "Adresse de réponse", "da-DK": "Svaradresse", "cs-CZ": "Adresa pro odpovědi", "ar-EG": "عنوان الرد", "zh-CN": "回复地址", "zh-TW": "回覆地址" },
  "Retired": { "de-DE": "Außer Kraft", "fr-FR": "Retirée", "da-DK": "Udgået", "cs-CZ": "Zrušeno", "ar-EG": "ملغاة", "zh-CN": "已停用", "zh-TW": "已停用" },
  "Review note": { "de-DE": "Durchsichtsnotiz", "fr-FR": "Note de relecture", "da-DK": "Gennemsynsnote", "cs-CZ": "Poznámka ke kontrole", "ar-EG": "ملاحظة المراجعة", "zh-CN": "审阅留言", "zh-TW": "審閱留言" },
  "Review notes": { "de-DE": "Durchsichtsnotizen", "fr-FR": "Notes de relecture", "da-DK": "Gennemsynsnoter", "cs-CZ": "Poznámky ke kontrole", "ar-EG": "ملاحظات المراجعة", "zh-CN": "审阅留言", "zh-TW": "審閱留言" },
  "Reviewed": { "de-DE": "Durchgesehen", "fr-FR": "Relu", "da-DK": "Gennemset", "cs-CZ": "Zkontrolováno", "ar-EG": "رُوجع", "zh-CN": "审阅时间", "zh-TW": "審閱時間" },
  "Revision of": { "de-DE": "Überarbeitung von", "fr-FR": "Révision de", "da-DK": "Revision af", "cs-CZ": "Revize", "ar-EG": "مراجعة لـ", "zh-CN": "修订自", "zh-TW": "修訂自" },
  "Role": { "de-DE": "Rolle", "fr-FR": "Rôle", "da-DK": "Rolle", "cs-CZ": "Role", "ar-EG": "الدور", "zh-CN": "职位", "zh-TW": "職位" },
  "Same": { "de-DE": "Unverändert", "fr-FR": "Inchangée", "da-DK": "Uændret", "cs-CZ": "Beze změny", "ar-EG": "بلا تغيير", "zh-CN": "未变", "zh-TW": "未變" },
  "Scope": { "de-DE": "Umfang", "fr-FR": "Périmètre", "da-DK": "Omfang", "cs-CZ": "Rozsah", "ar-EG": "النطاق", "zh-CN": "范围", "zh-TW": "範圍" },
  "Second reminder": { "de-DE": "Zweite Erinnerung", "fr-FR": "Deuxième rappel", "da-DK": "Anden påmindelse", "cs-CZ": "Druhá připomínka", "ar-EG": "التذكير الثاني", "zh-CN": "第二次提醒", "zh-TW": "第二次提醒" },
  "Sent": { "de-DE": "Gesendet", "fr-FR": "Envoyé", "da-DK": "Sendt", "cs-CZ": "Odesláno", "ar-EG": "أُرسل", "zh-CN": "已发送", "zh-TW": "已送出" },
  "Sent on": { "de-DE": "Gesendet am", "fr-FR": "Envoyé le", "da-DK": "Sendt den", "cs-CZ": "Odesláno dne", "ar-EG": "تاريخ الإرسال", "zh-CN": "发送时间", "zh-TW": "送出時間" },
  "Settings row": { "de-DE": "Einstellungszeile", "fr-FR": "Ligne de réglages", "da-DK": "Indstillingsrække", "cs-CZ": "Řádek nastavení", "ar-EG": "صف الإعدادات", "zh-CN": "设置行", "zh-TW": "設定列" },
  "Share of the proposal": { "de-DE": "Anteil am Angebot", "fr-FR": "Part de la proposition", "da-DK": "Andel af tilbuddet", "cs-CZ": "Podíl z nabídky", "ar-EG": "الحصة من العرض", "zh-CN": "提案占比", "zh-TW": "提案占比" },
  "Shared": { "de-DE": "Geteilt", "fr-FR": "Partagé", "da-DK": "Delt", "cs-CZ": "Sdíleno", "ar-EG": "مشارك", "zh-CN": "共享时间", "zh-TW": "分享時間" },
  "Shown to clients": { "de-DE": "Für Kunden sichtbar", "fr-FR": "Visible des clients", "da-DK": "Vist for kunder", "cs-CZ": "Zobrazeno klientům", "ar-EG": "ظاهر للعملاء", "zh-CN": "对客户可见", "zh-TW": "對客戶可見" },
  "Signed": { "de-DE": "Unterschrieben", "fr-FR": "Signé", "da-DK": "Underskrevet", "cs-CZ": "Podepsáno", "ar-EG": "وُقّع", "zh-CN": "签署时间", "zh-TW": "簽署時間" },
  "Signed by": { "de-DE": "Unterschrieben von", "fr-FR": "Signé par", "da-DK": "Underskrevet af", "cs-CZ": "Podepsal", "ar-EG": "وقّعه", "zh-CN": "签署人", "zh-TW": "簽署人" },
  "Signed with": { "de-DE": "Unterschrieben mit", "fr-FR": "Signé avec", "da-DK": "Underskrevet med", "cs-CZ": "Podepsáno s", "ar-EG": "وُقّع بـ", "zh-CN": "签署邮箱", "zh-TW": "簽署信箱" },
  "Skipped": { "de-DE": "Übersprungen", "fr-FR": "Ignoré", "da-DK": "Sprunget over", "cs-CZ": "Vynecháno", "ar-EG": "تم التخطي", "zh-CN": "已跳过", "zh-TW": "已略過" },
  "Stage": { "de-DE": "Etappe", "fr-FR": "Étape", "da-DK": "Etape", "cs-CZ": "Etapa", "ar-EG": "المرحلة", "zh-CN": "阶段", "zh-TW": "階段" },
  "Standard": { "de-DE": "Normal", "fr-FR": "Standard", "da-DK": "Standard", "cs-CZ": "Standardní", "ar-EG": "عادي", "zh-CN": "标准", "zh-TW": "標準" },
  "Started": { "de-DE": "Begonnen", "fr-FR": "Commencé", "da-DK": "Startet", "cs-CZ": "Zahájeno", "ar-EG": "بدأ", "zh-CN": "开始日期", "zh-TW": "開始日期" },
  "State": { "de-DE": "Stand", "fr-FR": "État", "da-DK": "Tilstand", "cs-CZ": "Stav", "ar-EG": "الحالة", "zh-CN": "状态", "zh-TW": "狀態" },
  "Statement": { "de-DE": "Kontoauszug", "fr-FR": "Relevé", "da-DK": "Kontoudtog", "cs-CZ": "Výpis", "ar-EG": "كشف الحساب", "zh-CN": "对账明细", "zh-TW": "對帳明細" },
  "Status": { "de-DE": "Status", "fr-FR": "Statut", "da-DK": "Status", "cs-CZ": "Stav", "ar-EG": "الحالة", "zh-CN": "状态", "zh-TW": "狀態" },
  "Still owed": { "de-DE": "Noch offen", "fr-FR": "Reste dû", "da-DK": "Stadig skyldig", "cs-CZ": "Zbývá uhradit", "ar-EG": "المتبقي", "zh-CN": "尚欠", "zh-TW": "尚欠" },
  "Studio mark": { "de-DE": "Studio-Zeichen", "fr-FR": "Logo du studio", "da-DK": "Studiets logo", "cs-CZ": "Logo studia", "ar-EG": "شعار الاستوديو", "zh-CN": "工作室标志", "zh-TW": "工作室標誌" },
  "Studio name": { "de-DE": "Name des Studios", "fr-FR": "Nom du studio", "da-DK": "Studiets navn", "cs-CZ": "Název studia", "ar-EG": "اسم الاستوديو", "zh-CN": "工作室名称", "zh-TW": "工作室名稱" },
  "Studio settings": { "de-DE": "Studio-Einstellungen", "fr-FR": "Réglages du studio", "da-DK": "Studieindstillinger", "cs-CZ": "Nastavení studia", "ar-EG": "إعدادات الاستوديو", "zh-CN": "工作室设置", "zh-TW": "工作室設定" },
  "Subject as approved": { "de-DE": "Betreff wie freigegeben", "fr-FR": "Objet tel que validé", "da-DK": "Emne som godkendt", "cs-CZ": "Předmět ve schváleném znění", "ar-EG": "الموضوع كما اعتُمد", "zh-CN": "批准后的主题", "zh-TW": "核准後的主旨" },
  "Subtotal": { "de-DE": "Zwischensumme", "fr-FR": "Sous-total", "da-DK": "Subtotal", "cs-CZ": "Mezisoučet", "ar-EG": "المجموع الفرعي", "zh-CN": "小计", "zh-TW": "小計" },
  "Tax": { "de-DE": "Steuer", "fr-FR": "Taxe", "da-DK": "Moms", "cs-CZ": "Daň", "ar-EG": "الضريبة", "zh-CN": "税", "zh-TW": "稅" },
  "Tax amount": { "de-DE": "Steuerbetrag", "fr-FR": "Montant de la taxe", "da-DK": "Momsbeløb", "cs-CZ": "Výše daně", "ar-EG": "مبلغ الضريبة", "zh-CN": "税额", "zh-TW": "稅額" },
  "Tax number": { "de-DE": "Steuernummer", "fr-FR": "Numéro fiscal", "da-DK": "Momsnummer", "cs-CZ": "DIČ", "ar-EG": "الرقم الضريبي", "zh-CN": "税号", "zh-TW": "統一編號" },
  "Tax rate": { "de-DE": "Steuersatz", "fr-FR": "Taux de taxe", "da-DK": "Momssats", "cs-CZ": "Sazba daně", "ar-EG": "نسبة الضريبة", "zh-CN": "税率", "zh-TW": "稅率" },
  "Tell us about new enquiries": { "de-DE": "Über neue Anfragen informieren", "fr-FR": "Nous prévenir des nouvelles demandes", "da-DK": "Giv besked om nye henvendelser", "cs-CZ": "Upozornit nás na nové poptávky", "ar-EG": "أخبرنا بالاستفسارات الجديدة", "zh-CN": "有新询价时通知我们", "zh-TW": "有新詢價時通知我們" },
  "Tell us when a brief is sent": { "de-DE": "Informieren, wenn ein Briefing gesendet wird", "fr-FR": "Nous prévenir quand un brief est envoyé", "da-DK": "Giv besked, når en brief sendes", "cs-CZ": "Upozornit nás na odeslaný brief", "ar-EG": "أخبرنا عند إرسال موجز", "zh-CN": "简报发送时通知我们", "zh-TW": "簡報送出時通知我們" },
  "Tell us when a client asks for a new price": { "de-DE": "Informieren, wenn ein Kunde einen neuen Preis anfragt", "fr-FR": "Nous prévenir quand un client demande un nouveau prix", "da-DK": "Giv besked, når en kunde beder om en ny pris", "cs-CZ": "Upozornit nás, když klient žádá novou cenu", "ar-EG": "أخبرنا عندما يطلب عميل سعرًا جديدًا", "zh-CN": "客户请求新报价时通知我们", "zh-TW": "客戶請求新報價時通知我們" },
  "Tell us when a client says they have paid": { "de-DE": "Informieren, wenn ein Kunde eine Zahlung meldet", "fr-FR": "Nous prévenir quand un client dit avoir payé", "da-DK": "Giv besked, når en kunde siger, de har betalt", "cs-CZ": "Upozornit nás, když klient uvede, že zaplatil", "ar-EG": "أخبرنا عندما يقول عميل إنه دفع", "zh-CN": "客户称已付款时通知我们", "zh-TW": "客戶稱已付款時通知我們" },
  "Tell us when a client writes a note": { "de-DE": "Informieren, wenn ein Kunde eine Notiz schreibt", "fr-FR": "Nous prévenir quand un client écrit une note", "da-DK": "Giv besked, når en kunde skriver en note", "cs-CZ": "Upozornit nás na poznámku od klienta", "ar-EG": "أخبرنا عندما يكتب عميل ملاحظة", "zh-CN": "客户留言时通知我们", "zh-TW": "客戶留言時通知我們" },
  "Tell us when a proposal is accepted": { "de-DE": "Informieren, wenn ein Angebot angenommen wird", "fr-FR": "Nous prévenir quand une proposition est acceptée", "da-DK": "Giv besked, når et tilbud accepteres", "cs-CZ": "Upozornit nás na přijatou nabídku", "ar-EG": "أخبرنا عند قبول عرض", "zh-CN": "提案被接受时通知我们", "zh-TW": "提案被接受時通知我們" },
  "Tell us when a proposal is declined": { "de-DE": "Informieren, wenn ein Angebot abgelehnt wird", "fr-FR": "Nous prévenir quand une proposition est refusée", "da-DK": "Giv besked, når et tilbud afvises", "cs-CZ": "Upozornit nás na odmítnutou nabídku", "ar-EG": "أخبرنا عند رفض عرض", "zh-CN": "提案被拒绝时通知我们", "zh-TW": "提案被拒絕時通知我們" },
  "Tell us when work is approved or sent back": { "de-DE": "Informieren, wenn Arbeit freigegeben oder zurückgeschickt wird", "fr-FR": "Nous prévenir quand un travail est validé ou renvoyé", "da-DK": "Giv besked, når arbejde godkendes eller sendes tilbage", "cs-CZ": "Upozornit nás na schválenou či vrácenou práci", "ar-EG": "أخبرنا عند اعتماد عمل أو إعادته", "zh-CN": "作品被批准或退回时通知我们", "zh-TW": "作品被核准或退回時通知我們" },
  "Terms": { "de-DE": "Bedingungen", "fr-FR": "Conditions", "da-DK": "Vilkår", "cs-CZ": "Podmínky", "ar-EG": "الشروط", "zh-CN": "条款", "zh-TW": "條款" },
  "Terms version": { "de-DE": "Version der Bedingungen", "fr-FR": "Version des conditions", "da-DK": "Version af vilkårene", "cs-CZ": "Verze podmínek", "ar-EG": "إصدار الشروط", "zh-CN": "条款版本", "zh-TW": "條款版本" },
  "Terms versions": { "de-DE": "Versionen der Bedingungen", "fr-FR": "Versions des conditions", "da-DK": "Versioner af vilkårene", "cs-CZ": "Verze podmínek", "ar-EG": "إصدارات الشروط", "zh-CN": "条款版本", "zh-TW": "條款版本" },
  "Text": { "de-DE": "Text", "fr-FR": "Texte", "da-DK": "Tekst", "cs-CZ": "Text", "ar-EG": "النص", "zh-CN": "正文", "zh-TW": "內文" },
  "The client": { "de-DE": "Der Kunde", "fr-FR": "Le client", "da-DK": "Kunden", "cs-CZ": "Klient", "ar-EG": "العميل", "zh-CN": "客户", "zh-TW": "客戶" },
  "The portal": { "de-DE": "Das Portal", "fr-FR": "Le portail", "da-DK": "Portalen", "cs-CZ": "Portál", "ar-EG": "البوابة", "zh-CN": "门户", "zh-TW": "入口網站" },
  "The studio": { "de-DE": "Das Studio", "fr-FR": "Le studio", "da-DK": "Studiet", "cs-CZ": "Studio", "ar-EG": "الاستوديو", "zh-CN": "工作室", "zh-TW": "工作室" },
  "Third reminder": { "de-DE": "Dritte Erinnerung", "fr-FR": "Troisième rappel", "da-DK": "Tredje påmindelse", "cs-CZ": "Třetí připomínka", "ar-EG": "التذكير الثالث", "zh-CN": "第三次提醒", "zh-TW": "第三次提醒" },
  "Title": { "de-DE": "Titel", "fr-FR": "Titre", "da-DK": "Titel", "cs-CZ": "Název", "ar-EG": "العنوان", "zh-CN": "标题", "zh-TW": "標題" },
  "To": { "de-DE": "An", "fr-FR": "À", "da-DK": "Til", "cs-CZ": "Komu", "ar-EG": "إلى", "zh-CN": "收件人", "zh-TW": "收件人" },
  "Total": { "de-DE": "Summe", "fr-FR": "Total", "da-DK": "I alt", "cs-CZ": "Celkem", "ar-EG": "الإجمالي", "zh-CN": "合计", "zh-TW": "合計" },
  "Trade": { "de-DE": "Branche", "fr-FR": "Secteur", "da-DK": "Branche", "cs-CZ": "Obor", "ar-EG": "المجال", "zh-CN": "行业", "zh-TW": "行業" },
  "Version": { "de-DE": "Version", "fr-FR": "Version", "da-DK": "Version", "cs-CZ": "Verze", "ar-EG": "الإصدار", "zh-CN": "版本", "zh-TW": "版本" },
  "Versions": { "de-DE": "Versionen", "fr-FR": "Versions", "da-DK": "Versioner", "cs-CZ": "Verze", "ar-EG": "الإصدارات", "zh-CN": "版本", "zh-TW": "版本" },
  "Void": { "de-DE": "Storniert", "fr-FR": "Annulée", "da-DK": "Annulleret", "cs-CZ": "Stornováno", "ar-EG": "ملغاة", "zh-CN": "已作废", "zh-TW": "已作廢" },
  "Voided": { "de-DE": "Storniert", "fr-FR": "Annulé", "da-DK": "Annulleret", "cs-CZ": "Stornováno", "ar-EG": "أُلغي", "zh-CN": "已作废", "zh-TW": "已作廢" },
  "Voided by": { "de-DE": "Storniert von", "fr-FR": "Annulé par", "da-DK": "Annulleret af", "cs-CZ": "Stornoval", "ar-EG": "ألغاه", "zh-CN": "作废人", "zh-TW": "作廢人" },
  "Voided on": { "de-DE": "Storniert am", "fr-FR": "Annulé le", "da-DK": "Annulleret den", "cs-CZ": "Stornováno dne", "ar-EG": "تاريخ الإلغاء", "zh-CN": "作废时间", "zh-TW": "作廢時間" },
  "Waiting for approval": { "de-DE": "Wartet auf Freigabe", "fr-FR": "En attente de validation", "da-DK": "Venter på godkendelse", "cs-CZ": "Čeká na schválení", "ar-EG": "في انتظار الموافقة", "zh-CN": "待批准", "zh-TW": "待核准" },
  "Waiting for review": { "de-DE": "Wartet auf Durchsicht", "fr-FR": "En attente de relecture", "da-DK": "Venter på gennemsyn", "cs-CZ": "Čeká na kontrolu", "ar-EG": "في انتظار المراجعة", "zh-CN": "待审阅", "zh-TW": "待審閱" },
  "Website": { "de-DE": "Website", "fr-FR": "Site web", "da-DK": "Hjemmeside", "cs-CZ": "Web", "ar-EG": "الموقع الإلكتروني", "zh-CN": "网站", "zh-TW": "網站" },
  "What changed": { "de-DE": "Was sich geändert hat", "fr-FR": "Ce qui a changé", "da-DK": "Hvad der er ændret", "cs-CZ": "Co se změnilo", "ar-EG": "ما الذي تغيّر", "zh-CN": "变更内容", "zh-TW": "變更內容" },
  "What it is": { "de-DE": "Was es ist", "fr-FR": "Libellé", "da-DK": "Hvad det er", "cs-CZ": "Co to je", "ar-EG": "ما هو", "zh-CN": "项目", "zh-TW": "項目" },
  "What the client said about paying": { "de-DE": "Was der Kunde zur Zahlung schrieb", "fr-FR": "Ce que le client a dit sur le paiement", "da-DK": "Hvad kunden skrev om betalingen", "cs-CZ": "Co klient napsal o platbě", "ar-EG": "ما قاله العميل عن الدفع", "zh-CN": "客户关于付款的说明", "zh-TW": "客戶關於付款的說明" },
  "What they said": { "de-DE": "Was sie geschrieben haben", "fr-FR": "Ce qu’ils ont dit", "da-DK": "Hvad de skrev", "cs-CZ": "Co napsali", "ar-EG": "ما قالوه", "zh-CN": "他们的意见", "zh-TW": "他們的意見" },
  "What they wrote": { "de-DE": "Was sie geschrieben haben", "fr-FR": "Ce qu’ils ont écrit", "da-DK": "Hvad de skrev", "cs-CZ": "Co napsali", "ar-EG": "ما كتبوه", "zh-CN": "他们的留言", "zh-TW": "他們的留言" },
  "When they want to start": { "de-DE": "Wann sie beginnen möchten", "fr-FR": "Quand ils veulent commencer", "da-DK": "Hvornår de vil starte", "cs-CZ": "Kdy chtějí začít", "ar-EG": "متى يريدون البدء", "zh-CN": "希望开始时间", "zh-TW": "希望開始時間" },
  "Why it is paused": { "de-DE": "Warum es pausiert ist", "fr-FR": "Pourquoi il est en pause", "da-DK": "Hvorfor det er sat på pause", "cs-CZ": "Proč je pozastaven", "ar-EG": "سبب الإيقاف المؤقت", "zh-CN": "暂停原因", "zh-TW": "暫停原因" },
  "Why it was not sent": { "de-DE": "Warum es nicht gesendet wurde", "fr-FR": "Pourquoi il n’a pas été envoyé", "da-DK": "Hvorfor den ikke blev sendt", "cs-CZ": "Proč nebyl odeslán", "ar-EG": "سبب عدم الإرسال", "zh-CN": "未发送原因", "zh-TW": "未送出原因" },
  "Why it was skipped": { "de-DE": "Warum es übersprungen wurde", "fr-FR": "Pourquoi il a été ignoré", "da-DK": "Hvorfor den blev sprunget over", "cs-CZ": "Proč byl vynechán", "ar-EG": "سبب التخطي", "zh-CN": "跳过原因", "zh-TW": "略過原因" },
  "Why it was voided": { "de-DE": "Warum es storniert wurde", "fr-FR": "Motif de l’annulation", "da-DK": "Hvorfor den blev annulleret", "cs-CZ": "Důvod storna", "ar-EG": "سبب الإلغاء", "zh-CN": "作废原因", "zh-TW": "作廢原因" },
  "Why it was withdrawn": { "de-DE": "Warum es zurückgezogen wurde", "fr-FR": "Motif du retrait", "da-DK": "Hvorfor det blev trukket tilbage", "cs-CZ": "Důvod stažení", "ar-EG": "سبب السحب", "zh-CN": "撤回原因", "zh-TW": "撤回原因" },
  "Why the follow-up was refused": { "de-DE": "Warum der Folgeschritt abgelehnt wurde", "fr-FR": "Pourquoi la suite a été refusée", "da-DK": "Hvorfor opfølgningen blev afvist", "cs-CZ": "Proč byl navazující krok odmítnut", "ar-EG": "سبب رفض المتابعة", "zh-CN": "后续被拒原因", "zh-TW": "後續被拒原因" },
  "Why they declined": { "de-DE": "Warum sie abgelehnt haben", "fr-FR": "Pourquoi ils ont refusé", "da-DK": "Hvorfor de afviste", "cs-CZ": "Proč odmítli", "ar-EG": "سبب الرفض", "zh-CN": "拒绝原因", "zh-TW": "拒絕原因" },
  "Withdrawn": { "de-DE": "Zurückgezogen", "fr-FR": "Retirée", "da-DK": "Trukket tilbage", "cs-CZ": "Staženo", "ar-EG": "مسحوب", "zh-CN": "已撤回", "zh-TW": "已撤回" },
  "Words as approved": { "de-DE": "Text wie freigegeben", "fr-FR": "Texte tel que validé", "da-DK": "Tekst som godkendt", "cs-CZ": "Text ve schváleném znění", "ar-EG": "النص كما اعتُمد", "zh-CN": "批准后的正文", "zh-TW": "核准後的內文" },
  "Work in progress": { "de-DE": "Laufende Arbeit", "fr-FR": "Travaux en cours", "da-DK": "Igangværende arbejde", "cs-CZ": "Rozpracovaná práce", "ar-EG": "العمل الجاري", "zh-CN": "进行中的工作", "zh-TW": "進行中的工作" },
  "Written": { "de-DE": "Geschrieben", "fr-FR": "Écrit", "da-DK": "Skrevet", "cs-CZ": "Napsáno", "ar-EG": "كُتب", "zh-CN": "撰写时间", "zh-TW": "撰寫時間" },
  "Written by": { "de-DE": "Geschrieben von", "fr-FR": "Écrit par", "da-DK": "Skrevet af", "cs-CZ": "Napsal", "ar-EG": "كتبه", "zh-CN": "撰写人", "zh-TW": "撰寫人" },
};
