/**
 * The demo card's words, and the demo's own toasts, in the eight languages
 * the card speaks — `demo.json`'s labels (`demo-card.ts`) and what the
 * bridge says when the card acts (`demoBridge.ts`).
 *
 * DEMO BUILD ONLY: nothing in a real build imports this file, and the build
 * test's deny-list holds every phrase here out of the surfaces.
 */
import type { DemoLocale } from "../demo-types.ts";

type Words = Record<string, string>;

const EN: Words = {
  "demo.persona.studio": "Studio",
  "demo.persona.client": "Client",

  "demo.screen.home": "Home",
  "demo.screen.enquiries": "Enquiries",
  "demo.screen.proposals": "Proposals",
  "demo.screen.composer": "Composer",
  "demo.screen.terms": "Terms",
  "demo.screen.projects": "Projects",
  "demo.screen.project": "Project",
  "demo.screen.review": "Review",
  "demo.screen.handover": "Handover",
  "demo.screen.clients": "Clients",
  "demo.screen.client": "Client",
  "demo.screen.invoices": "Invoices",
  "demo.screen.invoice": "Invoice",
  "demo.screen.chasing": "Chasing",
  "demo.screen.print": "Print",
  "demo.screen.settings": "Settings",
  "demo.screen.notfound": "404",
  "demo.screen.entry": "Sign in",
  "demo.screen.chome": "Home",
  "demo.screen.cproposal": "Proposal",
  "demo.screen.cproject": "Project",
  "demo.screen.cinvoice": "Invoice",
  "demo.screen.cstatement": "Statement",
  "demo.screen.cbrief": "Brief",
  "demo.screen.cwrap": "Shared handover",
  "demo.screen.cna": "Not available",

  "demo.do.amara": "Amara · Hearth & Loaf",
  "demo.do.unknownAddress": "An address we don’t know",
  "demo.do.openLink": "Open the emailed link",
  "demo.do.expireLink": "Let the link expire",
  "demo.do.outOfDate": "Show an out-of-date one",
  "demo.do.pausedWork": "Paused work",
  "demo.do.alreadyPaid": "An invoice already paid",
  "demo.do.callComesIn": "A call comes in",
  "demo.do.sampleProposal": "Fill a sample proposal",
  "demo.do.acceptsAndSigns": "The client accepts and signs",
  "demo.do.asksForChanges": "The client asks for changes",
  "demo.do.approves": "The client approves",
  "demo.do.partPayment": "Part payment",
  "demo.do.saysPaid": "The client says they paid",

  "demo.clock.week": "+1 week",
  "demo.clock.reset": "Back to 28 July",

  "demo.toast.now": "It is now {day}.",
  "demo.toast.reset": "Back to {day}, with the sample data as it was.",
  "demo.toast.accepted": "{client} accepted and signed {number} in the portal.",
  "demo.toast.notWaiting": "{number} isn’t waiting on a decision.",
  "demo.toast.recorded": "Recorded {amount} against {number}.",
  "demo.toast.saysPaid": "{client} says they paid {number}.",
  "demo.toast.openInvoice": "Open a sent invoice with a balance first.",
  "demo.toast.changesAsked": "{client} asked for changes on “{title}”.",
  "demo.toast.approved": "{client} approved “{title}”.",
  "demo.toast.openProject": "Open a project with work waiting on the client first.",
  "demo.toast.linkExpired": "The emailed link has expired.",

  "demo.fill.changesNote": "Could the wordmark sit a little heavier on the bag?",
  "demo.fill.paidNote": "Sent by bank transfer today.",
  "demo.fill.callBody": "Rang about labels for a new cider — would like a call back this week.",
  "demo.fill.proposalTitle": "Season two artwork",
  "demo.fill.proposalScope": "Artwork for every episode of the second season, in the pilot’s style, and one key image for the season.",
  "demo.fill.lineEpisode": "Episode artwork",
  "demo.fill.lineKeyArt": "Season key art",
};

const DE: Words = {
  "demo.persona.studio": "Studio",
  "demo.persona.client": "Kunde",
  "demo.screen.home": "Start",
  "demo.screen.enquiries": "Anfragen",
  "demo.screen.proposals": "Angebote",
  "demo.screen.composer": "Editor",
  "demo.screen.terms": "Bedingungen",
  "demo.screen.projects": "Projekte",
  "demo.screen.project": "Projekt",
  "demo.screen.review": "Abstimmung",
  "demo.screen.handover": "Übergabe",
  "demo.screen.clients": "Kunden",
  "demo.screen.client": "Kunde",
  "demo.screen.invoices": "Rechnungen",
  "demo.screen.invoice": "Rechnung",
  "demo.screen.chasing": "Mahnwesen",
  "demo.screen.print": "Druck",
  "demo.screen.settings": "Einstellungen",
  "demo.screen.notfound": "404",
  "demo.screen.entry": "Anmelden",
  "demo.screen.chome": "Start",
  "demo.screen.cproposal": "Angebot",
  "demo.screen.cproject": "Projekt",
  "demo.screen.cinvoice": "Rechnung",
  "demo.screen.cstatement": "Kontoauszug",
  "demo.screen.cbrief": "Briefing",
  "demo.screen.cwrap": "Geteilte Übergabe",
  "demo.screen.cna": "Nicht verfügbar",
  "demo.do.amara": "Amara · Hearth & Loaf",
  "demo.do.unknownAddress": "Eine unbekannte Adresse",
  "demo.do.openLink": "Den Link aus der E-Mail öffnen",
  "demo.do.expireLink": "Den Link ablaufen lassen",
  "demo.do.outOfDate": "Ein abgelaufenes zeigen",
  "demo.do.pausedWork": "Pausierte Arbeit",
  "demo.do.alreadyPaid": "Eine bereits bezahlte Rechnung",
  "demo.do.callComesIn": "Ein Anruf kommt herein",
  "demo.do.sampleProposal": "Ein Beispielangebot ausfüllen",
  "demo.do.acceptsAndSigns": "Der Kunde nimmt an und unterschreibt",
  "demo.do.asksForChanges": "Der Kunde bittet um Änderungen",
  "demo.do.approves": "Der Kunde gibt frei",
  "demo.do.partPayment": "Teilzahlung",
  "demo.do.saysPaid": "Der Kunde meldet eine Zahlung",
  "demo.clock.week": "+1 Woche",
  "demo.clock.reset": "Zurück zum 28. Juli",
  "demo.toast.now": "Es ist jetzt {day}.",
  "demo.toast.reset": "Zurück zu {day}, mit den Beispieldaten wie zuvor.",
  "demo.toast.accepted": "{client} hat {number} im Portal angenommen und unterschrieben.",
  "demo.toast.notWaiting": "{number} wartet auf keine Entscheidung.",
  "demo.toast.recorded": "{amount} zu {number} erfasst.",
  "demo.toast.saysPaid": "{client} meldet, {number} bezahlt zu haben.",
  "demo.toast.openInvoice": "Öffnen Sie zuerst eine gesendete Rechnung mit offenem Betrag.",
  "demo.toast.changesAsked": "{client} bittet um Änderungen an „{title}“.",
  "demo.toast.approved": "{client} hat „{title}“ freigegeben.",
  "demo.toast.openProject": "Öffnen Sie zuerst ein Projekt, bei dem Arbeit auf den Kunden wartet.",
  "demo.toast.linkExpired": "Der Link aus der E-Mail ist abgelaufen.",
  "demo.fill.changesNote": "Könnte die Wortmarke auf der Tüte etwas kräftiger stehen?",
  "demo.fill.paidNote": "Heute per Überweisung gesendet.",
  "demo.fill.callBody": "Hat wegen Etiketten für einen neuen Cidre angerufen — bittet diese Woche um Rückruf.",
  "demo.fill.proposalTitle": "Artwork für Staffel zwei",
  "demo.fill.proposalScope": "Artwork für jede Folge der zweiten Staffel im Stil des Piloten und ein Schlüsselbild für die Staffel.",
  "demo.fill.lineEpisode": "Folgen-Artwork",
  "demo.fill.lineKeyArt": "Schlüsselbild der Staffel",
};

const FR: Words = {
  "demo.persona.studio": "Studio",
  "demo.persona.client": "Client",
  "demo.screen.home": "Accueil",
  "demo.screen.enquiries": "Demandes",
  "demo.screen.proposals": "Propositions",
  "demo.screen.composer": "Rédaction",
  "demo.screen.terms": "Conditions",
  "demo.screen.projects": "Projets",
  "demo.screen.project": "Projet",
  "demo.screen.review": "Relecture",
  "demo.screen.handover": "Remise",
  "demo.screen.clients": "Clients",
  "demo.screen.client": "Client",
  "demo.screen.invoices": "Factures",
  "demo.screen.invoice": "Facture",
  "demo.screen.chasing": "Relances",
  "demo.screen.print": "Impression",
  "demo.screen.settings": "Réglages",
  "demo.screen.notfound": "404",
  "demo.screen.entry": "Connexion",
  "demo.screen.chome": "Accueil",
  "demo.screen.cproposal": "Proposition",
  "demo.screen.cproject": "Projet",
  "demo.screen.cinvoice": "Facture",
  "demo.screen.cstatement": "Relevé",
  "demo.screen.cbrief": "Brief",
  "demo.screen.cwrap": "Remise partagée",
  "demo.screen.cna": "Indisponible",
  "demo.do.amara": "Amara · Hearth & Loaf",
  "demo.do.unknownAddress": "Une adresse inconnue",
  "demo.do.openLink": "Ouvrir le lien reçu par e-mail",
  "demo.do.expireLink": "Laisser le lien expirer",
  "demo.do.outOfDate": "En montrer une expirée",
  "demo.do.pausedWork": "Travail en pause",
  "demo.do.alreadyPaid": "Une facture déjà réglée",
  "demo.do.callComesIn": "Un appel arrive",
  "demo.do.sampleProposal": "Remplir une proposition d’exemple",
  "demo.do.acceptsAndSigns": "Le client accepte et signe",
  "demo.do.asksForChanges": "Le client demande des modifications",
  "demo.do.approves": "Le client valide",
  "demo.do.partPayment": "Paiement partiel",
  "demo.do.saysPaid": "Le client dit avoir payé",
  "demo.clock.week": "+1 semaine",
  "demo.clock.reset": "Retour au 28 juillet",
  "demo.toast.now": "Nous sommes le {day}.",
  "demo.toast.reset": "Retour au {day}, avec les données d’exemple d’origine.",
  "demo.toast.accepted": "{client} a accepté et signé {number} dans le portail.",
  "demo.toast.notWaiting": "{number} n’attend aucune décision.",
  "demo.toast.recorded": "{amount} enregistré sur {number}.",
  "demo.toast.saysPaid": "{client} dit avoir réglé {number}.",
  "demo.toast.openInvoice": "Ouvrez d’abord une facture envoyée avec un solde.",
  "demo.toast.changesAsked": "{client} demande des modifications sur « {title} ».",
  "demo.toast.approved": "{client} a validé « {title} ».",
  "demo.toast.openProject": "Ouvrez d’abord un projet dont un travail attend le client.",
  "demo.toast.linkExpired": "Le lien reçu par e-mail a expiré.",
  "demo.fill.changesNote": "Le logotype pourrait-il être un peu plus appuyé sur le sac ?",
  "demo.fill.paidNote": "Envoyé par virement aujourd’hui.",
  "demo.fill.callBody": "A appelé pour les étiquettes d’un nouveau cidre — souhaite être rappelé cette semaine.",
  "demo.fill.proposalTitle": "Visuels de la saison deux",
  "demo.fill.proposalScope": "Un visuel pour chaque épisode de la deuxième saison, dans le style du pilote, et une image principale pour la saison.",
  "demo.fill.lineEpisode": "Visuel d’épisode",
  "demo.fill.lineKeyArt": "Image principale de la saison",
};

const DA: Words = {
  "demo.persona.studio": "Studie",
  "demo.persona.client": "Kunde",
  "demo.screen.home": "Forside",
  "demo.screen.enquiries": "Henvendelser",
  "demo.screen.proposals": "Tilbud",
  "demo.screen.composer": "Skriv",
  "demo.screen.terms": "Vilkår",
  "demo.screen.projects": "Projekter",
  "demo.screen.project": "Projekt",
  "demo.screen.review": "Gennemsyn",
  "demo.screen.handover": "Aflevering",
  "demo.screen.clients": "Kunder",
  "demo.screen.client": "Kunde",
  "demo.screen.invoices": "Fakturaer",
  "demo.screen.invoice": "Faktura",
  "demo.screen.chasing": "Rykkere",
  "demo.screen.print": "Udskrift",
  "demo.screen.settings": "Indstillinger",
  "demo.screen.notfound": "404",
  "demo.screen.entry": "Log ind",
  "demo.screen.chome": "Forside",
  "demo.screen.cproposal": "Tilbud",
  "demo.screen.cproject": "Projekt",
  "demo.screen.cinvoice": "Faktura",
  "demo.screen.cstatement": "Kontoudtog",
  "demo.screen.cbrief": "Brief",
  "demo.screen.cwrap": "Delt aflevering",
  "demo.screen.cna": "Ikke tilgængelig",
  "demo.do.amara": "Amara · Hearth & Loaf",
  "demo.do.unknownAddress": "En adresse, vi ikke kender",
  "demo.do.openLink": "Åbn linket fra e-mailen",
  "demo.do.expireLink": "Lad linket udløbe",
  "demo.do.outOfDate": "Vis et udløbet",
  "demo.do.pausedWork": "Arbejde på pause",
  "demo.do.alreadyPaid": "En faktura, der allerede er betalt",
  "demo.do.callComesIn": "Et opkald kommer ind",
  "demo.do.sampleProposal": "Udfyld et eksempeltilbud",
  "demo.do.acceptsAndSigns": "Kunden accepterer og underskriver",
  "demo.do.asksForChanges": "Kunden beder om ændringer",
  "demo.do.approves": "Kunden godkender",
  "demo.do.partPayment": "Delbetaling",
  "demo.do.saysPaid": "Kunden siger, de har betalt",
  "demo.clock.week": "+1 uge",
  "demo.clock.reset": "Tilbage til 28. juli",
  "demo.toast.now": "Det er nu {day}.",
  "demo.toast.reset": "Tilbage til {day} med eksempeldataene, som de var.",
  "demo.toast.accepted": "{client} har accepteret og underskrevet {number} i portalen.",
  "demo.toast.notWaiting": "{number} venter ikke på en beslutning.",
  "demo.toast.recorded": "{amount} registreret på {number}.",
  "demo.toast.saysPaid": "{client} siger, at {number} er betalt.",
  "demo.toast.openInvoice": "Åbn først en sendt faktura med en saldo.",
  "demo.toast.changesAsked": "{client} har bedt om ændringer til “{title}”.",
  "demo.toast.approved": "{client} har godkendt “{title}”.",
  "demo.toast.openProject": "Åbn først et projekt med arbejde, der venter på kunden.",
  "demo.toast.linkExpired": "Linket fra e-mailen er udløbet.",
  "demo.fill.changesNote": "Kan ordmærket stå lidt kraftigere på posen?",
  "demo.fill.paidNote": "Sendt med bankoverførsel i dag.",
  "demo.fill.callBody": "Ringede om etiketter til en ny cider — vil gerne ringes op i denne uge.",
  "demo.fill.proposalTitle": "Grafik til sæson to",
  "demo.fill.proposalScope": "Grafik til hvert afsnit af anden sæson i pilotens stil og ét nøglebillede til sæsonen.",
  "demo.fill.lineEpisode": "Afsnitsgrafik",
  "demo.fill.lineKeyArt": "Sæsonens nøglebillede",
};

const CS: Words = {
  "demo.persona.studio": "Studio",
  "demo.persona.client": "Klient",
  "demo.screen.home": "Přehled",
  "demo.screen.enquiries": "Poptávky",
  "demo.screen.proposals": "Nabídky",
  "demo.screen.composer": "Editor",
  "demo.screen.terms": "Podmínky",
  "demo.screen.projects": "Projekty",
  "demo.screen.project": "Projekt",
  "demo.screen.review": "Kontrola",
  "demo.screen.handover": "Předání",
  "demo.screen.clients": "Klienti",
  "demo.screen.client": "Klient",
  "demo.screen.invoices": "Faktury",
  "demo.screen.invoice": "Faktura",
  "demo.screen.chasing": "Upomínky",
  "demo.screen.print": "Tisk",
  "demo.screen.settings": "Nastavení",
  "demo.screen.notfound": "404",
  "demo.screen.entry": "Přihlášení",
  "demo.screen.chome": "Přehled",
  "demo.screen.cproposal": "Nabídka",
  "demo.screen.cproject": "Projekt",
  "demo.screen.cinvoice": "Faktura",
  "demo.screen.cstatement": "Výpis",
  "demo.screen.cbrief": "Brief",
  "demo.screen.cwrap": "Sdílené předání",
  "demo.screen.cna": "Nedostupné",
  "demo.do.amara": "Amara · Hearth & Loaf",
  "demo.do.unknownAddress": "Adresa, kterou neznáme",
  "demo.do.openLink": "Otevřít odkaz z e-mailu",
  "demo.do.expireLink": "Nechat odkaz vypršet",
  "demo.do.outOfDate": "Ukázat prošlou",
  "demo.do.pausedWork": "Pozastavená práce",
  "demo.do.alreadyPaid": "Už zaplacená faktura",
  "demo.do.callComesIn": "Přichází hovor",
  "demo.do.sampleProposal": "Vyplnit ukázkovou nabídku",
  "demo.do.acceptsAndSigns": "Klient přijímá a podepisuje",
  "demo.do.asksForChanges": "Klient žádá o změny",
  "demo.do.approves": "Klient schvaluje",
  "demo.do.partPayment": "Částečná platba",
  "demo.do.saysPaid": "Klient uvádí, že zaplatil",
  "demo.clock.week": "+1 týden",
  "demo.clock.reset": "Zpět na 28. července",
  "demo.toast.now": "Teď je {day}.",
  "demo.toast.reset": "Zpět na {day}, s ukázkovými daty jako na začátku.",
  "demo.toast.accepted": "{client} přijal a podepsal {number} v portálu.",
  "demo.toast.notWaiting": "{number} nečeká na rozhodnutí.",
  "demo.toast.recorded": "Zaznamenáno {amount} k {number}.",
  "demo.toast.saysPaid": "{client} uvádí, že zaplatil {number}.",
  "demo.toast.openInvoice": "Nejdřív otevřete odeslanou fakturu s nedoplatkem.",
  "demo.toast.changesAsked": "{client} žádá o změny u „{title}“.",
  "demo.toast.approved": "{client} schválil „{title}“.",
  "demo.toast.openProject": "Nejdřív otevřete projekt, kde práce čeká na klienta.",
  "demo.toast.linkExpired": "Odkaz z e-mailu vypršel.",
  "demo.fill.changesNote": "Mohlo by logo na tašce působit o něco výrazněji?",
  "demo.fill.paidNote": "Dnes odesláno bankovním převodem.",
  "demo.fill.callBody": "Volali kvůli etiketám na nový cider — prosí o zavolání tento týden.",
  "demo.fill.proposalTitle": "Grafika ke druhé řadě",
  "demo.fill.proposalScope": "Grafika ke každému dílu druhé řady ve stylu pilotu a jeden hlavní obraz celé řady.",
  "demo.fill.lineEpisode": "Grafika k dílu",
  "demo.fill.lineKeyArt": "Hlavní obraz řady",
};

const AR: Words = {
  "demo.persona.studio": "الاستوديو",
  "demo.persona.client": "العميل",
  "demo.screen.home": "الرئيسية",
  "demo.screen.enquiries": "الاستفسارات",
  "demo.screen.proposals": "العروض",
  "demo.screen.composer": "المحرر",
  "demo.screen.terms": "الشروط",
  "demo.screen.projects": "المشاريع",
  "demo.screen.project": "المشروع",
  "demo.screen.review": "المراجعة",
  "demo.screen.handover": "التسليم",
  "demo.screen.clients": "العملاء",
  "demo.screen.client": "العميل",
  "demo.screen.invoices": "الفواتير",
  "demo.screen.invoice": "الفاتورة",
  "demo.screen.chasing": "المتابعة",
  "demo.screen.print": "الطباعة",
  "demo.screen.settings": "الإعدادات",
  "demo.screen.notfound": "404",
  "demo.screen.entry": "تسجيل الدخول",
  "demo.screen.chome": "الرئيسية",
  "demo.screen.cproposal": "العرض",
  "demo.screen.cproject": "المشروع",
  "demo.screen.cinvoice": "الفاتورة",
  "demo.screen.cstatement": "كشف الحساب",
  "demo.screen.cbrief": "الموجز",
  "demo.screen.cwrap": "تسليم مشترك",
  "demo.screen.cna": "غير متاح",
  "demo.do.amara": "Amara · Hearth & Loaf",
  "demo.do.unknownAddress": "عنوان لا نعرفه",
  "demo.do.openLink": "افتح الرابط المرسل بالبريد",
  "demo.do.expireLink": "دع الرابط تنتهي صلاحيته",
  "demo.do.outOfDate": "اعرض عرضًا منتهيًا",
  "demo.do.pausedWork": "عمل متوقف",
  "demo.do.alreadyPaid": "فاتورة مدفوعة بالفعل",
  "demo.do.callComesIn": "مكالمة واردة",
  "demo.do.sampleProposal": "املأ عرضًا نموذجيًا",
  "demo.do.acceptsAndSigns": "العميل يقبل ويوقّع",
  "demo.do.asksForChanges": "العميل يطلب تعديلات",
  "demo.do.approves": "العميل يعتمد",
  "demo.do.partPayment": "دفعة جزئية",
  "demo.do.saysPaid": "العميل يقول إنه دفع",
  "demo.clock.week": "+أسبوع",
  "demo.clock.reset": "العودة إلى ٢٨ يوليو",
  "demo.toast.now": "اليوم هو {day}.",
  "demo.toast.reset": "عدنا إلى {day}، والبيانات النموذجية كما كانت.",
  "demo.toast.accepted": "قبل {client} العرض {number} ووقّعه في البوابة.",
  "demo.toast.notWaiting": "{number} لا ينتظر قرارًا.",
  "demo.toast.recorded": "سُجّل {amount} على {number}.",
  "demo.toast.saysPaid": "يقول {client} إنه دفع {number}.",
  "demo.toast.openInvoice": "افتح أولًا فاتورة مرسلة عليها رصيد.",
  "demo.toast.changesAsked": "طلب {client} تعديلات على «{title}».",
  "demo.toast.approved": "اعتمد {client} «{title}».",
  "demo.toast.openProject": "افتح أولًا مشروعًا فيه عمل ينتظر العميل.",
  "demo.toast.linkExpired": "انتهت صلاحية الرابط المرسل بالبريد.",
  "demo.fill.changesNote": "هل يمكن أن يظهر الشعار أثقل قليلًا على الكيس؟",
  "demo.fill.paidNote": "أُرسل بتحويل مصرفي اليوم.",
  "demo.fill.callBody": "اتصل بشأن ملصقات لنوع جديد من عصير التفاح — يرجو معاودة الاتصال هذا الأسبوع.",
  "demo.fill.proposalTitle": "رسومات الموسم الثاني",
  "demo.fill.proposalScope": "رسومات لكل حلقة من الموسم الثاني بأسلوب الحلقة التجريبية، وصورة رئيسية واحدة للموسم.",
  "demo.fill.lineEpisode": "رسومات الحلقة",
  "demo.fill.lineKeyArt": "الصورة الرئيسية للموسم",
};

const ZH_CN: Words = {
  "demo.persona.studio": "工作室",
  "demo.persona.client": "客户",
  "demo.screen.home": "首页",
  "demo.screen.enquiries": "询价",
  "demo.screen.proposals": "提案",
  "demo.screen.composer": "编辑",
  "demo.screen.terms": "条款",
  "demo.screen.projects": "项目",
  "demo.screen.project": "项目",
  "demo.screen.review": "审阅",
  "demo.screen.handover": "交接",
  "demo.screen.clients": "客户",
  "demo.screen.client": "客户",
  "demo.screen.invoices": "发票",
  "demo.screen.invoice": "发票",
  "demo.screen.chasing": "催款",
  "demo.screen.print": "打印",
  "demo.screen.settings": "设置",
  "demo.screen.notfound": "404",
  "demo.screen.entry": "登录",
  "demo.screen.chome": "首页",
  "demo.screen.cproposal": "提案",
  "demo.screen.cproject": "项目",
  "demo.screen.cinvoice": "发票",
  "demo.screen.cstatement": "对账明细",
  "demo.screen.cbrief": "简报",
  "demo.screen.cwrap": "共享交接",
  "demo.screen.cna": "不可用",
  "demo.do.amara": "Amara · Hearth & Loaf",
  "demo.do.unknownAddress": "一个我们不认识的地址",
  "demo.do.openLink": "打开邮件中的链接",
  "demo.do.expireLink": "让链接过期",
  "demo.do.outOfDate": "显示一份已过期的",
  "demo.do.pausedWork": "暂停的工作",
  "demo.do.alreadyPaid": "一张已付清的发票",
  "demo.do.callComesIn": "来了一个电话",
  "demo.do.sampleProposal": "填写示例提案",
  "demo.do.acceptsAndSigns": "客户接受并签署",
  "demo.do.asksForChanges": "客户要求修改",
  "demo.do.approves": "客户批准",
  "demo.do.partPayment": "部分付款",
  "demo.do.saysPaid": "客户称已付款",
  "demo.clock.week": "+1 周",
  "demo.clock.reset": "回到 7 月 28 日",
  "demo.toast.now": "现在是 {day}。",
  "demo.toast.reset": "回到 {day}，示例数据恢复原样。",
  "demo.toast.accepted": "{client} 已在门户中接受并签署 {number}。",
  "demo.toast.notWaiting": "{number} 没有在等待决定。",
  "demo.toast.recorded": "已在 {number} 上记录 {amount}。",
  "demo.toast.saysPaid": "{client} 称已支付 {number}。",
  "demo.toast.openInvoice": "请先打开一张有余额的已发送发票。",
  "demo.toast.changesAsked": "{client} 要求修改“{title}”。",
  "demo.toast.approved": "{client} 已批准“{title}”。",
  "demo.toast.openProject": "请先打开一个有工作在等客户的项目。",
  "demo.toast.linkExpired": "邮件中的链接已过期。",
  "demo.fill.changesNote": "袋子上的字标能再醒目一点吗？",
  "demo.fill.paidNote": "今天已通过银行转账汇出。",
  "demo.fill.callBody": "来电询问新款苹果酒的标签——希望本周回电。",
  "demo.fill.proposalTitle": "第二季视觉",
  "demo.fill.proposalScope": "按试播集的风格为第二季每一集制作视觉，并为本季制作一张主视觉。",
  "demo.fill.lineEpisode": "单集视觉",
  "demo.fill.lineKeyArt": "本季主视觉",
};

const ZH_TW: Words = {
  "demo.persona.studio": "工作室",
  "demo.persona.client": "客戶",
  "demo.screen.home": "首頁",
  "demo.screen.enquiries": "詢價",
  "demo.screen.proposals": "提案",
  "demo.screen.composer": "編輯",
  "demo.screen.terms": "條款",
  "demo.screen.projects": "專案",
  "demo.screen.project": "專案",
  "demo.screen.review": "審閱",
  "demo.screen.handover": "交接",
  "demo.screen.clients": "客戶",
  "demo.screen.client": "客戶",
  "demo.screen.invoices": "發票",
  "demo.screen.invoice": "發票",
  "demo.screen.chasing": "催款",
  "demo.screen.print": "列印",
  "demo.screen.settings": "設定",
  "demo.screen.notfound": "404",
  "demo.screen.entry": "登入",
  "demo.screen.chome": "首頁",
  "demo.screen.cproposal": "提案",
  "demo.screen.cproject": "專案",
  "demo.screen.cinvoice": "發票",
  "demo.screen.cstatement": "對帳明細",
  "demo.screen.cbrief": "簡報",
  "demo.screen.cwrap": "共享交接",
  "demo.screen.cna": "無法使用",
  "demo.do.amara": "Amara · Hearth & Loaf",
  "demo.do.unknownAddress": "一個我們不認識的地址",
  "demo.do.openLink": "開啟郵件中的連結",
  "demo.do.expireLink": "讓連結過期",
  "demo.do.outOfDate": "顯示一份已過期的",
  "demo.do.pausedWork": "暫停的工作",
  "demo.do.alreadyPaid": "一張已付清的發票",
  "demo.do.callComesIn": "來了一通電話",
  "demo.do.sampleProposal": "填寫範例提案",
  "demo.do.acceptsAndSigns": "客戶接受並簽署",
  "demo.do.asksForChanges": "客戶要求修改",
  "demo.do.approves": "客戶核准",
  "demo.do.partPayment": "部分付款",
  "demo.do.saysPaid": "客戶稱已付款",
  "demo.clock.week": "+1 週",
  "demo.clock.reset": "回到 7 月 28 日",
  "demo.toast.now": "現在是 {day}。",
  "demo.toast.reset": "回到 {day}，範例資料恢復原樣。",
  "demo.toast.accepted": "{client} 已在入口網站接受並簽署 {number}。",
  "demo.toast.notWaiting": "{number} 沒有在等待決定。",
  "demo.toast.recorded": "已在 {number} 上記錄 {amount}。",
  "demo.toast.saysPaid": "{client} 稱已支付 {number}。",
  "demo.toast.openInvoice": "請先開啟一張有餘額的已寄出發票。",
  "demo.toast.changesAsked": "{client} 要求修改「{title}」。",
  "demo.toast.approved": "{client} 已核准「{title}」。",
  "demo.toast.openProject": "請先開啟一個有工作在等客戶的專案。",
  "demo.toast.linkExpired": "郵件中的連結已過期。",
  "demo.fill.changesNote": "袋子上的字標能再醒目一點嗎？",
  "demo.fill.paidNote": "今天已透過銀行轉帳匯出。",
  "demo.fill.callBody": "來電詢問新款蘋果酒的標籤——希望本週回電。",
  "demo.fill.proposalTitle": "第二季視覺",
  "demo.fill.proposalScope": "依試播集的風格為第二季每一集製作視覺，並為本季製作一張主視覺。",
  "demo.fill.lineEpisode": "單集視覺",
  "demo.fill.lineKeyArt": "本季主視覺",
};

/** Every demo key in every language the card speaks: `{ 'en-US': { key: text } … }`. */
export const DEMO_MESSAGES: Record<DemoLocale, Words> = {
  "en-US": EN,
  "de-DE": DE,
  "fr-FR": FR,
  "da-DK": DA,
  "cs-CZ": CS,
  "ar-EG": AR,
  "zh-CN": ZH_CN,
  "zh-TW": ZH_TW,
};

/** A demo phrase in `locale` (its language's, else English), with `{name}` filled. */
export function demoText(key: string, locale: string, vars: Record<string, string> = {}): string {
  const words = (DEMO_MESSAGES as Record<string, Words>)[locale] ?? (DEMO_MESSAGES as Record<string, Words>)[`${locale.split("-")[0] ?? ""}`] ?? EN;
  const text = words[key] ?? EN[key] ?? key;
  return text.replace(/\{(\w+)\}/g, (whole, name: string) => vars[name] ?? whole);
}
